package com.s4fmer.boozecraft.reg;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.s4fmer.boozecraft.BoozeCraft;
import com.s4fmer.boozecraft.drink.DrinkDef;
import com.s4fmer.boozecraft.drink.DrinkItem;
import com.s4fmer.boozecraft.drink.Drinks;
import com.s4fmer.boozecraft.item.ShakerItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

/** GENERATED by tools/boozecraft_gen.py - item registry. */
public final class BoozeItems {

	public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(BoozeCraft.MODID);

	/** Creative tab order, filled while the fields below are initialised. */
	public static final List<DeferredItem<? extends Item>> CREATIVE_ORDER = new ArrayList<>();
	private static final Map<String, DeferredItem<Item>> DRINKS = new LinkedHashMap<>();

	// ---- glassware and tools ----
	public static final DeferredItem<Item> GLASS_CUP = tool("glass_cup", 16);
	public static final DeferredItem<Item> MUG = tool("mug", 16);
	public static final DeferredItem<Item> SHOT_GLASS = tool("shot_glass", 16);
	public static final DeferredItem<Item> EMPTY_CAN = tool("empty_can", 64);
	public static final DeferredItem<Item> SHAKER = shaker("shaker");
	public static final DeferredItem<Item> COFFEE_BEANS = tool("coffee_beans", 64);
	public static final DeferredItem<Item> YEAST = tool("yeast", 64);
	public static final DeferredItem<Item> SODA_SYRUP = tool("soda_syrup", 16);
	public static final DeferredItem<Item> ENERGY_SYRUP = tool("energy_syrup", 16);


	// ---- mash ----
	public static final DeferredItem<Item> MASH_GRAIN = drink(Drinks.MASH_GRAIN, 16);
	public static final DeferredItem<Item> MASH_POTATO = drink(Drinks.MASH_POTATO, 16);
	public static final DeferredItem<Item> MASH_SUGAR = drink(Drinks.MASH_SUGAR, 16);
	public static final DeferredItem<Item> MASH_FRUIT = drink(Drinks.MASH_FRUIT, 16);
	public static final DeferredItem<Item> MASH_BERRY = drink(Drinks.MASH_BERRY, 16);
	public static final DeferredItem<Item> MASH_MELON = drink(Drinks.MASH_MELON, 16);
	public static final DeferredItem<Item> MASH_CACTUS = drink(Drinks.MASH_CACTUS, 16);
	public static final DeferredItem<Item> MASH_HONEY = drink(Drinks.MASH_HONEY, 16);
	public static final DeferredItem<Item> MASH_MUSHROOM = drink(Drinks.MASH_MUSHROOM, 16);
	public static final DeferredItem<Item> MASH_CHORUS = drink(Drinks.MASH_CHORUS, 16);
	public static final DeferredItem<Item> MASH_GLOW = drink(Drinks.MASH_GLOW, 16);
	public static final DeferredItem<Item> MASH_PUMPKIN = drink(Drinks.MASH_PUMPKIN, 16);

	// ---- beer ----
	public static final DeferredItem<Item> BEER_LIGHT = drink(Drinks.BEER_LIGHT, 16);
	public static final DeferredItem<Item> BEER_DARK = drink(Drinks.BEER_DARK, 16);
	public static final DeferredItem<Item> CIDER = drink(Drinks.CIDER, 16);
	public static final DeferredItem<Item> BRAGA = drink(Drinks.BRAGA, 16);
	public static final DeferredItem<Item> POTATO_BREW = drink(Drinks.POTATO_BREW, 16);
	public static final DeferredItem<Item> MUSHROOM_ALE = drink(Drinks.MUSHROOM_ALE, 16);
	public static final DeferredItem<Item> PUMPKIN_ALE = drink(Drinks.PUMPKIN_ALE, 16);

	// ---- wine ----
	public static final DeferredItem<Item> MEAD = drink(Drinks.MEAD, 16);
	public static final DeferredItem<Item> BERRY_WINE = drink(Drinks.BERRY_WINE, 16);
	public static final DeferredItem<Item> MELON_WINE = drink(Drinks.MELON_WINE, 16);
	public static final DeferredItem<Item> CACTUS_WINE = drink(Drinks.CACTUS_WINE, 16);
	public static final DeferredItem<Item> CHORUS_WINE = drink(Drinks.CHORUS_WINE, 16);
	public static final DeferredItem<Item> GLOW_WINE = drink(Drinks.GLOW_WINE, 16);
	public static final DeferredItem<Item> SAKE = drink(Drinks.SAKE, 16);

	// ---- spirit ----
	public static final DeferredItem<Item> MOONSHINE = drink(Drinks.MOONSHINE, 16);
	public static final DeferredItem<Item> VODKA = drink(Drinks.VODKA, 16);
	public static final DeferredItem<Item> WHITE_RUM = drink(Drinks.WHITE_RUM, 16);
	public static final DeferredItem<Item> RUM = drink(Drinks.RUM, 16);
	public static final DeferredItem<Item> WHISKEY = drink(Drinks.WHISKEY, 16);
	public static final DeferredItem<Item> NETHER_WHISKEY = drink(Drinks.NETHER_WHISKEY, 16);
	public static final DeferredItem<Item> BRANDY = drink(Drinks.BRANDY, 16);
	public static final DeferredItem<Item> COGNAC = drink(Drinks.COGNAC, 16);
	public static final DeferredItem<Item> TEQUILA = drink(Drinks.TEQUILA, 16);
	public static final DeferredItem<Item> GIN = drink(Drinks.GIN, 16);
	public static final DeferredItem<Item> ABSINTHE = drink(Drinks.ABSINTHE, 16);
	public static final DeferredItem<Item> DRAGON_ABSINTHE = drink(Drinks.DRAGON_ABSINTHE, 16);
	public static final DeferredItem<Item> SCHNAPPS = drink(Drinks.SCHNAPPS, 16);
	public static final DeferredItem<Item> SAMBUCA = drink(Drinks.SAMBUCA, 16);
	public static final DeferredItem<Item> EVERCLEAR = drink(Drinks.EVERCLEAR, 16);

	// ---- cocktail ----
	public static final DeferredItem<Item> RUM_COLA = drink(Drinks.RUM_COLA, 16);
	public static final DeferredItem<Item> WHISKEY_COLA = drink(Drinks.WHISKEY_COLA, 16);
	public static final DeferredItem<Item> VODKA_ENERGY = drink(Drinks.VODKA_ENERGY, 16);
	public static final DeferredItem<Item> SCREWDRIVER = drink(Drinks.SCREWDRIVER, 16);
	public static final DeferredItem<Item> GIN_TONIC = drink(Drinks.GIN_TONIC, 16);
	public static final DeferredItem<Item> MOJITO = drink(Drinks.MOJITO, 16);
	public static final DeferredItem<Item> MARGARITA = drink(Drinks.MARGARITA, 16);
	public static final DeferredItem<Item> BLACK_RUSSIAN = drink(Drinks.BLACK_RUSSIAN, 16);
	public static final DeferredItem<Item> IRISH_COFFEE = drink(Drinks.IRISH_COFFEE, 16);
	public static final DeferredItem<Item> SANGRIA = drink(Drinks.SANGRIA, 16);
	public static final DeferredItem<Item> BERRY_DAIQUIRI = drink(Drinks.BERRY_DAIQUIRI, 16);
	public static final DeferredItem<Item> ABSINTHE_BOMB = drink(Drinks.ABSINTHE_BOMB, 16);
	public static final DeferredItem<Item> MOONSHINE_PUNCH = drink(Drinks.MOONSHINE_PUNCH, 16);
	public static final DeferredItem<Item> LONG_ISLAND = drink(Drinks.LONG_ISLAND, 16);
	public static final DeferredItem<Item> TEQUILA_SUNRISE = drink(Drinks.TEQUILA_SUNRISE, 16);
	public static final DeferredItem<Item> DIRTY_SWILL = drink(Drinks.DIRTY_SWILL, 16);

	// ---- soda ----
	public static final DeferredItem<Item> COLA = drink(Drinks.COLA, 16);
	public static final DeferredItem<Item> ORANGE_SODA = drink(Drinks.ORANGE_SODA, 16);
	public static final DeferredItem<Item> LEMON_LIME_SODA = drink(Drinks.LEMON_LIME_SODA, 16);
	public static final DeferredItem<Item> SODA_WATER = drink(Drinks.SODA_WATER, 16);

	// ---- energy ----
	public static final DeferredItem<Item> ENERGY_CLASSIC = drink(Drinks.ENERGY_CLASSIC, 16);
	public static final DeferredItem<Item> ENERGY_WHITE = drink(Drinks.ENERGY_WHITE, 16);
	public static final DeferredItem<Item> ENERGY_MANGO = drink(Drinks.ENERGY_MANGO, 16);

	// ---- coffee ----
	public static final DeferredItem<Item> COFFEE = drink(Drinks.COFFEE, 16);
	public static final DeferredItem<Item> ESPRESSO = drink(Drinks.ESPRESSO, 16);
	public static final DeferredItem<Item> LATTE = drink(Drinks.LATTE, 16);
	public static final DeferredItem<Item> HOT_COCOA = drink(Drinks.HOT_COCOA, 16);
	public static final DeferredItem<Item> SWEET_TEA = drink(Drinks.SWEET_TEA, 16);

	// ---- juice ----
	public static final DeferredItem<Item> APPLE_JUICE = drink(Drinks.APPLE_JUICE, 16);
	public static final DeferredItem<Item> ORANGE_JUICE = drink(Drinks.ORANGE_JUICE, 16);
	public static final DeferredItem<Item> BERRY_JUICE = drink(Drinks.BERRY_JUICE, 16);
	public static final DeferredItem<Item> MELON_JUICE = drink(Drinks.MELON_JUICE, 16);
	public static final DeferredItem<Item> LEMONADE = drink(Drinks.LEMONADE, 16);
	public static final DeferredItem<Item> MILKSHAKE = drink(Drinks.MILKSHAKE, 16);

	// ---- medicine ----
	public static final DeferredItem<Item> HANGOVER_CURE = drink(Drinks.HANGOVER_CURE, 16);
	public static final DeferredItem<Item> ASPIRIN = drink(Drinks.ASPIRIN, 16);

	// ---- blocks ----
	public static final DeferredItem<Item> FERMENTER = blockItem("fermenter", BoozeBlocks.FERMENTER);
	public static final DeferredItem<Item> STILL = blockItem("still", BoozeBlocks.STILL);
	public static final DeferredItem<Item> AGING_BARREL = blockItem("aging_barrel", BoozeBlocks.AGING_BARREL);
	public static final DeferredItem<Item> BAR_COUNTER = blockItem("bar_counter", BoozeBlocks.BAR_COUNTER);

	private static DeferredItem<Item> tool(String name, int stackSize) {
		DeferredItem<Item> item = ITEMS.register(name, () -> new Item(new Item.Properties().stacksTo(stackSize)));
		CREATIVE_ORDER.add(item);
		return item;
	}

	private static DeferredItem<Item> shaker(String name) {
		DeferredItem<Item> item = ITEMS.register(name, () -> new ShakerItem(new Item.Properties().stacksTo(1)));
		CREATIVE_ORDER.add(item);
		return item;
	}

	private static DeferredItem<Item> drink(DrinkDef def, int stackSize) {
		DeferredItem<Item> item = ITEMS.register(def.id(),
				() -> new DrinkItem(def, new Item.Properties().stacksTo(stackSize)));
		CREATIVE_ORDER.add(item);
		DRINKS.put(def.id(), item);
		return item;
	}

	private static DeferredItem<Item> blockItem(String name, DeferredBlock<Block> block) {
		DeferredItem<Item> item = ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
		CREATIVE_ORDER.add(item);
		return item;
	}

	/** Registered drink item by drink id, or null. */
	public static DeferredItem<Item> drink(String id) {
		return DRINKS.get(id);
	}

	public static Map<String, DeferredItem<Item>> drinks() {
		return DRINKS;
	}

	private BoozeItems() {
	}
}
