plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.107'
}

def minecraft_version = providers.gradleProperty('minecraft_version').get()
def neo_version = providers.gradleProperty('neo_version').get()
def mod_id = providers.gradleProperty('mod_id').get()

group = 'dev.riftspotify'
version = providers.gradleProperty('mod_version').get()

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

neoForge {
    version = neo_version

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

jar {
    manifest {
        attributes([
            'Specification-Title': 'Rift Spotify',
            'Specification-Vendor': 'Rift Spotify',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'Rift Spotify'
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
