<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RootNamespace>ScavPrototypeSexMod</RootNamespace>
        <AssemblyName>ScavPrototypeSexMod</AssemblyName>
        <LangVersion>latest</LangVersion>
        <Deterministic>true</Deterministic>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <OutputPath>C:\Program Files (x86)\Steam\steamapps\common\Casualties Unknown Demo\BepInEx\plugins</OutputPath>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <WarningLevel>5</WarningLevel>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <OutputPath>bin\Release\</OutputPath>
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>Libraries\Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="NAudio">
            <HintPath>Libraries\NAudio.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="NAudio.Core">
            <HintPath>Libraries\NAudio.Core.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="NAudio.WinMM">
            <HintPath>Libraries\NAudio.WinMM.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="NAudio.Wasapi">
            <HintPath>Libraries\NAudio.Wasapi.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>Libraries\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>Libraries\Unity.TextMeshPro.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>Libraries\UnityEngine.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.AnimationModule">
            <HintPath>Libraries\UnityEngine.AnimationModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>Libraries\UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>Libraries\UnityEngine.AudioModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>Libraries\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>Libraries\UnityEngine.ImageConversionModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.ParticleSystemModule">
            <HintPath>Libraries\UnityEngine.ParticleSystemModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.Physics2DModule">
            <HintPath>Libraries\UnityEngine.Physics2DModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>Libraries\UnityEngine.TextRenderingModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>Libraries\UnityEngine.UI.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>Libraries\UnityEngine.UIModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Assets\NewFolder\**" />
        <EmbeddedResource Remove="Assets\NewFolder\**" />
        <EmbeddedResource Remove="Libraries\**" />

        <EmbeddedResource Include="Assets\**\*" Exclude="Assets\**\*.meta" />
        <EmbeddedResource Include="Libraries\NAudio.Core.dll" />
        <EmbeddedResource Include="Libraries\NAudio.dll" />
        <EmbeddedResource Include="Libraries\NAudio.WinMM.dll" />
        <EmbeddedResource Include="Libraries\NAudio.Wasapi.dll" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Assets\locale\EN.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Core" Version="5.4.21" />
        <PackageReference Include="HarmonyX" Version="2.10.2" />
    </ItemGroup>
</Project>
