package com.s4fmer.boozecraft.drink;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import net.minecraft.world.effect.MobEffects;

/** GENERATED by tools/boozecraft_gen.py - every drink in the mod. */
public final class Drinks {

	private static final Map<String, DrinkDef> ALL = new LinkedHashMap<>();

	public static final DrinkDef MASH_GRAIN = add(DrinkDef.builder("mash_grain").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0xC9B37A).build());
	public static final DrinkDef MASH_POTATO = add(DrinkDef.builder("mash_potato").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0xD8C9A0).build());
	public static final DrinkDef MASH_SUGAR = add(DrinkDef.builder("mash_sugar").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0xF0EAD8).build());
	public static final DrinkDef MASH_FRUIT = add(DrinkDef.builder("mash_fruit").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0xC8D86A).build());
	public static final DrinkDef MASH_BERRY = add(DrinkDef.builder("mash_berry").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0x9B2A4A).build());
	public static final DrinkDef MASH_MELON = add(DrinkDef.builder("mash_melon").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0xE85A5A).build());
	public static final DrinkDef MASH_CACTUS = add(DrinkDef.builder("mash_cactus").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0x4A8A2A).build());
	public static final DrinkDef MASH_HONEY = add(DrinkDef.builder("mash_honey").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0xE0A82A).build());
	public static final DrinkDef MASH_MUSHROOM = add(DrinkDef.builder("mash_mushroom").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0x8B6A4A).build());
	public static final DrinkDef MASH_CHORUS = add(DrinkDef.builder("mash_chorus").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0x9B5AC9).build());
	public static final DrinkDef MASH_GLOW = add(DrinkDef.builder("mash_glow").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0xE8D84A).build());
	public static final DrinkDef MASH_PUMPKIN = add(DrinkDef.builder("mash_pumpkin").cat(DrinkCategory.MASH).vessel(Vessel.NONE).abv(0.00D)
			.color(0xE08A2A).build());
	public static final DrinkDef BEER_LIGHT = add(DrinkDef.builder("beer_light").cat(DrinkCategory.BEER).vessel(Vessel.MUG).abv(0.05D)
			.nutrition(1).addiction(0.5D).color(0xE9B44C).fx(MobEffects.MOVEMENT_SPEED, 20, 0).build());
	public static final DrinkDef BEER_DARK = add(DrinkDef.builder("beer_dark").cat(DrinkCategory.BEER).vessel(Vessel.MUG).abv(0.06D)
			.nutrition(2).addiction(0.6D).color(0x6B3A10).fx(MobEffects.DIG_SPEED, 25, 0).build());
	public static final DrinkDef CIDER = add(DrinkDef.builder("cider").cat(DrinkCategory.BEER).vessel(Vessel.MUG).abv(0.06D)
			.nutrition(2).addiction(0.6D).color(0xD9A72A).fx(MobEffects.REGENERATION, 8, 0).build());
	public static final DrinkDef BRAGA = add(DrinkDef.builder("braga").cat(DrinkCategory.BEER).vessel(Vessel.MUG).abv(0.09D)
			.nutrition(1).addiction(0.9D).color(0xC9B37A).fx(MobEffects.MOVEMENT_SPEED, 15, 0).build());
	public static final DrinkDef POTATO_BREW = add(DrinkDef.builder("potato_brew").cat(DrinkCategory.BEER).vessel(Vessel.MUG).abv(0.07D)
			.nutrition(2).addiction(0.7D).color(0xD8C9A0).fx(MobEffects.DIG_SPEED, 20, 0).build());
	public static final DrinkDef MUSHROOM_ALE = add(DrinkDef.builder("mushroom_ale").cat(DrinkCategory.BEER).vessel(Vessel.MUG).abv(0.08D)
			.nutrition(1).addiction(0.8D).color(0x8B6A4A).fx(MobEffects.NIGHT_VISION, 30, 0).build());
	public static final DrinkDef PUMPKIN_ALE = add(DrinkDef.builder("pumpkin_ale").cat(DrinkCategory.BEER).vessel(Vessel.MUG).abv(0.07D)
			.nutrition(2).addiction(0.7D).color(0xE08A2A).fx(MobEffects.ABSORPTION, 45, 0).build());
	public static final DrinkDef MEAD = add(DrinkDef.builder("mead").cat(DrinkCategory.WINE).vessel(Vessel.MUG).abv(0.12D)
			.nutrition(2).addiction(1.2D).color(0xE0A32E).fx(MobEffects.REGENERATION, 10, 0)
			.fx(MobEffects.ABSORPTION, 60, 0).build());
	public static final DrinkDef BERRY_WINE = add(DrinkDef.builder("berry_wine").cat(DrinkCategory.WINE).vessel(Vessel.BOTTLE).abv(0.13D)
			.nutrition(1).addiction(1.3D).color(0x7A1030).fx(MobEffects.LUCK, 60, 0).build());
	public static final DrinkDef MELON_WINE = add(DrinkDef.builder("melon_wine").cat(DrinkCategory.WINE).vessel(Vessel.BOTTLE).abv(0.11D)
			.nutrition(1).addiction(1.1D).color(0xE05A5A).fx(MobEffects.REGENERATION, 6, 1).build());
	public static final DrinkDef CACTUS_WINE = add(DrinkDef.builder("cactus_wine").cat(DrinkCategory.WINE).vessel(Vessel.BOTTLE).abv(0.12D)
			.addiction(1.2D).color(0x5A9E3A).fx(MobEffects.DAMAGE_RESISTANCE, 30, 0).build());
	public static final DrinkDef CHORUS_WINE = add(DrinkDef.builder("chorus_wine").cat(DrinkCategory.WINE).vessel(Vessel.BOTTLE).abv(0.14D)
			.addiction(1.4D).color(0xA36BC9).fx(MobEffects.SLOW_FALLING, 30, 0).build());
	public static final DrinkDef GLOW_WINE = add(DrinkDef.builder("glow_wine").cat(DrinkCategory.WINE).vessel(Vessel.BOTTLE).abv(0.13D)
			.addiction(1.3D).color(0xE8E45A).fx(MobEffects.GLOWING, 45, 0)
			.fx(MobEffects.NIGHT_VISION, 30, 0).build());
	public static final DrinkDef SAKE = add(DrinkDef.builder("sake").cat(DrinkCategory.WINE).vessel(Vessel.BOTTLE).abv(0.16D)
			.nutrition(1).addiction(1.6D).color(0xF2F2E0).fx(MobEffects.DAMAGE_BOOST, 40, 0).build());
	public static final DrinkDef MOONSHINE = add(DrinkDef.builder("moonshine").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.45D)
			.addiction(4.5D).color(0xF0F0E8).fx(MobEffects.DAMAGE_BOOST, 30, 0).build());
	public static final DrinkDef VODKA = add(DrinkDef.builder("vodka").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.40D)
			.addiction(4.0D).color(0xEAF6FF).fx(MobEffects.DAMAGE_BOOST, 45, 0)
			.fx(MobEffects.FIRE_RESISTANCE, 20, 0).build());
	public static final DrinkDef WHITE_RUM = add(DrinkDef.builder("white_rum").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.38D)
			.addiction(3.8D).color(0xF5EFD8).fx(MobEffects.MOVEMENT_SPEED, 45, 0).build());
	public static final DrinkDef RUM = add(DrinkDef.builder("rum").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.40D)
			.addiction(4.0D).color(0x8A4A18).fx(MobEffects.MOVEMENT_SPEED, 60, 0)
			.fx(MobEffects.DAMAGE_BOOST, 30, 0).build());
	public static final DrinkDef WHISKEY = add(DrinkDef.builder("whiskey").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.43D)
			.addiction(4.3D).color(0xC1651A).fx(MobEffects.DAMAGE_RESISTANCE, 45, 0)
			.fx(MobEffects.DAMAGE_BOOST, 30, 0).build());
	public static final DrinkDef NETHER_WHISKEY = add(DrinkDef.builder("nether_whiskey").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE)
			.abv(0.55D).addiction(5.5D).color(0xE03A10).fx(MobEffects.FIRE_RESISTANCE, 180, 0)
			.fx(MobEffects.DAMAGE_BOOST, 45, 1).build());
	public static final DrinkDef BRANDY = add(DrinkDef.builder("brandy").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.40D)
			.addiction(4.0D).color(0xA8541A).fx(MobEffects.REGENERATION, 10, 0)
			.fx(MobEffects.DAMAGE_RESISTANCE, 30, 0).build());
	public static final DrinkDef COGNAC = add(DrinkDef.builder("cognac").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.42D)
			.addiction(4.2D).color(0x8F3F12).fx(MobEffects.REGENERATION, 12, 1)
			.fx(MobEffects.LUCK, 120, 0).build());
	public static final DrinkDef TEQUILA = add(DrinkDef.builder("tequila").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.38D)
			.addiction(3.8D).color(0xEFE39A).fx(MobEffects.MOVEMENT_SPEED, 60, 1).build());
	public static final DrinkDef GIN = add(DrinkDef.builder("gin").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.40D)
			.addiction(4.0D).color(0xE6F2E8).fx(MobEffects.WATER_BREATHING, 60, 0)
			.fx(MobEffects.DOLPHINS_GRACE, 30, 0).build());
	public static final DrinkDef ABSINTHE = add(DrinkDef.builder("absinthe").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.60D)
			.addiction(6.0D).color(0x7ADB3A).fx(MobEffects.NIGHT_VISION, 120, 0)
			.fx(MobEffects.JUMP, 60, 1).build());
	public static final DrinkDef DRAGON_ABSINTHE = add(DrinkDef.builder("dragon_absinthe").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE)
			.abv(0.70D).addiction(7.0D).color(0x35E0B0).fx(MobEffects.NIGHT_VISION, 180, 0)
			.fx(MobEffects.SLOW_FALLING, 60, 0).fx(MobEffects.REGENERATION, 10, 1).build());
	public static final DrinkDef SCHNAPPS = add(DrinkDef.builder("schnapps").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.35D)
			.addiction(3.5D).color(0xEFE0C0).fx(MobEffects.JUMP, 45, 0).build());
	public static final DrinkDef SAMBUCA = add(DrinkDef.builder("sambuca").cat(DrinkCategory.SPIRIT).vessel(Vessel.SHOT).abv(0.38D)
			.addiction(3.8D).color(0xF0EAD0).fx(MobEffects.DIG_SPEED, 45, 1).build());
	public static final DrinkDef EVERCLEAR = add(DrinkDef.builder("everclear").cat(DrinkCategory.SPIRIT).vessel(Vessel.BOTTLE).abv(0.75D)
			.addiction(7.5D).color(0xFFFFFF).fx(MobEffects.DAMAGE_BOOST, 60, 1)
			.fx(MobEffects.FIRE_RESISTANCE, 30, 0).build());
	public static final DrinkDef RUM_COLA = add(DrinkDef.builder("rum_cola").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.14D)
			.addiction(1.4D).caffeine(15.0D).color(0x4A2410).fx(MobEffects.MOVEMENT_SPEED, 60, 0)
			.build());
	public static final DrinkDef WHISKEY_COLA = add(DrinkDef.builder("whiskey_cola").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.15D)
			.addiction(1.5D).caffeine(15.0D).color(0x5A2A10).fx(MobEffects.DAMAGE_RESISTANCE, 60, 0)
			.build());
	public static final DrinkDef VODKA_ENERGY = add(DrinkDef.builder("vodka_energy").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.16D)
			.addiction(1.6D).caffeine(40.0D).color(0x9BE03A).fx(MobEffects.MOVEMENT_SPEED, 90, 1)
			.fx(MobEffects.DIG_SPEED, 90, 0).build());
	public static final DrinkDef SCREWDRIVER = add(DrinkDef.builder("screwdriver").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.14D)
			.nutrition(1).addiction(1.4D).color(0xF29A1A).fx(MobEffects.REGENERATION, 8, 0).build());
	public static final DrinkDef GIN_TONIC = add(DrinkDef.builder("gin_tonic").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.13D)
			.addiction(1.3D).color(0xDFF3E0).fx(MobEffects.WATER_BREATHING, 90, 0).build());
	public static final DrinkDef MOJITO = add(DrinkDef.builder("mojito").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.12D)
			.addiction(1.2D).color(0xB9E86A).fx(MobEffects.MOVEMENT_SPEED, 60, 0)
			.fx(MobEffects.JUMP, 45, 0).build());
	public static final DrinkDef MARGARITA = add(DrinkDef.builder("margarita").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.15D)
			.addiction(1.5D).color(0xE8F0A0).fx(MobEffects.LUCK, 90, 0).build());
	public static final DrinkDef BLACK_RUSSIAN = add(DrinkDef.builder("black_russian").cat(DrinkCategory.COCKTAIL).vessel(Vessel.SHOT)
			.abv(0.22D).addiction(2.2D).caffeine(30.0D).color(0x2A1A10)
			.fx(MobEffects.DIG_SPEED, 60, 1).build());
	public static final DrinkDef IRISH_COFFEE = add(DrinkDef.builder("irish_coffee").cat(DrinkCategory.COCKTAIL).vessel(Vessel.MUG).abv(0.18D)
			.addiction(1.8D).caffeine(35.0D).color(0x6B4426).fx(MobEffects.DAMAGE_RESISTANCE, 60, 0)
			.build());
	public static final DrinkDef SANGRIA = add(DrinkDef.builder("sangria").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.11D)
			.nutrition(1).addiction(1.1D).color(0x9B1A3A).fx(MobEffects.LUCK, 120, 0)
			.fx(MobEffects.REGENERATION, 8, 0).build());
	public static final DrinkDef BERRY_DAIQUIRI = add(DrinkDef.builder("berry_daiquiri").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP)
			.abv(0.15D).nutrition(1).addiction(1.5D).color(0xD84A7A).fx(MobEffects.LUCK, 60, 0)
			.fx(MobEffects.MOVEMENT_SPEED, 45, 0).build());
	public static final DrinkDef ABSINTHE_BOMB = add(DrinkDef.builder("absinthe_bomb").cat(DrinkCategory.COCKTAIL).vessel(Vessel.SHOT)
			.abv(0.30D).addiction(3.0D).caffeine(45.0D).color(0x8AF04A)
			.fx(MobEffects.NIGHT_VISION, 120, 0).fx(MobEffects.JUMP, 60, 1).build());
	public static final DrinkDef MOONSHINE_PUNCH = add(DrinkDef.builder("moonshine_punch").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP)
			.abv(0.20D).nutrition(1).addiction(2.0D).color(0xF2C24A)
			.fx(MobEffects.DAMAGE_BOOST, 60, 1).fx(MobEffects.MOVEMENT_SPEED, 60, 0).build());
	public static final DrinkDef LONG_ISLAND = add(DrinkDef.builder("long_island").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP).abv(0.32D)
			.addiction(3.2D).color(0xB06A2A).fx(MobEffects.DAMAGE_BOOST, 90, 1)
			.fx(MobEffects.MOVEMENT_SPEED, 90, 0).build());
	public static final DrinkDef TEQUILA_SUNRISE = add(DrinkDef.builder("tequila_sunrise").cat(DrinkCategory.COCKTAIL).vessel(Vessel.CUP)
			.abv(0.14D).nutrition(1).addiction(1.4D).color(0xF06A2A)
			.fx(MobEffects.MOVEMENT_SPEED, 90, 1).build());
	public static final DrinkDef DIRTY_SWILL = add(DrinkDef.builder("dirty_swill").cat(DrinkCategory.COCKTAIL).vessel(Vessel.MUG).abv(0.35D)
			.addiction(3.5D).color(0x6A5A3A).fx(MobEffects.HUNGER, 30, 0).fx(MobEffects.POISON, 5, 0)
			.build());
	public static final DrinkDef COLA = add(DrinkDef.builder("cola").cat(DrinkCategory.SODA).vessel(Vessel.CAN).abv(0.00D)
			.nutrition(1).caffeine(12.0D).color(0x2A1408).fx(MobEffects.MOVEMENT_SPEED, 30, 0).build());
	public static final DrinkDef ORANGE_SODA = add(DrinkDef.builder("orange_soda").cat(DrinkCategory.SODA).vessel(Vessel.CAN).abv(0.00D)
			.nutrition(1).color(0xF08A10).build());
	public static final DrinkDef LEMON_LIME_SODA = add(DrinkDef.builder("lemon_lime_soda").cat(DrinkCategory.SODA).vessel(Vessel.CAN).abv(0.00D)
			.nutrition(1).color(0xC8E85A).build());
	public static final DrinkDef SODA_WATER = add(DrinkDef.builder("soda_water").cat(DrinkCategory.SODA).vessel(Vessel.BOTTLE).abv(0.00D)
			.sober(2.0D).color(0xDCEFF7).build());
	public static final DrinkDef ENERGY_CLASSIC = add(DrinkDef.builder("energy_classic").cat(DrinkCategory.ENERGY).vessel(Vessel.CAN).abv(0.00D)
			.caffeine(45.0D).color(0x121212).fx(MobEffects.MOVEMENT_SPEED, 90, 0)
			.fx(MobEffects.DIG_SPEED, 60, 0).build());
	public static final DrinkDef ENERGY_WHITE = add(DrinkDef.builder("energy_white").cat(DrinkCategory.ENERGY).vessel(Vessel.CAN).abv(0.00D)
			.caffeine(55.0D).color(0xF2F2F2).fx(MobEffects.MOVEMENT_SPEED, 120, 0)
			.fx(MobEffects.JUMP, 60, 0).build());
	public static final DrinkDef ENERGY_MANGO = add(DrinkDef.builder("energy_mango").cat(DrinkCategory.ENERGY).vessel(Vessel.CAN).abv(0.00D)
			.nutrition(1).caffeine(40.0D).color(0xF0B02A).fx(MobEffects.MOVEMENT_SPEED, 90, 0).build());
	public static final DrinkDef COFFEE = add(DrinkDef.builder("coffee").cat(DrinkCategory.COFFEE).vessel(Vessel.MUG).abv(0.00D)
			.caffeine(35.0D).sober(6.0D).color(0x4A2A18).fx(MobEffects.DIG_SPEED, 60, 0).build());
	public static final DrinkDef ESPRESSO = add(DrinkDef.builder("espresso").cat(DrinkCategory.COFFEE).vessel(Vessel.SHOT).abv(0.00D)
			.caffeine(50.0D).sober(10.0D).color(0x2A1810).fx(MobEffects.DIG_SPEED, 90, 1).build());
	public static final DrinkDef LATTE = add(DrinkDef.builder("latte").cat(DrinkCategory.COFFEE).vessel(Vessel.MUG).abv(0.00D)
			.nutrition(2).caffeine(30.0D).sober(5.0D).color(0xC9A882)
			.fx(MobEffects.MOVEMENT_SPEED, 45, 0).build());
	public static final DrinkDef HOT_COCOA = add(DrinkDef.builder("hot_cocoa").cat(DrinkCategory.COFFEE).vessel(Vessel.MUG).abv(0.00D)
			.nutrition(3).color(0x6B4426).fx(MobEffects.REGENERATION, 6, 0).build());
	public static final DrinkDef SWEET_TEA = add(DrinkDef.builder("sweet_tea").cat(DrinkCategory.COFFEE).vessel(Vessel.MUG).abv(0.00D)
			.nutrition(1).caffeine(12.0D).relief(3.0D).color(0xC98A3A).build());
	public static final DrinkDef APPLE_JUICE = add(DrinkDef.builder("apple_juice").cat(DrinkCategory.JUICE).vessel(Vessel.CUP).abv(0.00D)
			.nutrition(2).color(0xE8C24A).build());
	public static final DrinkDef ORANGE_JUICE = add(DrinkDef.builder("orange_juice").cat(DrinkCategory.JUICE).vessel(Vessel.CUP).abv(0.00D)
			.nutrition(2).color(0xF0921A).fx(MobEffects.NIGHT_VISION, 20, 0).build());
	public static final DrinkDef BERRY_JUICE = add(DrinkDef.builder("berry_juice").cat(DrinkCategory.JUICE).vessel(Vessel.CUP).abv(0.00D)
			.nutrition(2).color(0xC02A5A).build());
	public static final DrinkDef MELON_JUICE = add(DrinkDef.builder("melon_juice").cat(DrinkCategory.JUICE).vessel(Vessel.CUP).abv(0.00D)
			.nutrition(2).color(0xF06A6A).build());
	public static final DrinkDef LEMONADE = add(DrinkDef.builder("lemonade").cat(DrinkCategory.JUICE).vessel(Vessel.CUP).abv(0.00D)
			.nutrition(1).sober(3.0D).color(0xF2E86A).build());
	public static final DrinkDef MILKSHAKE = add(DrinkDef.builder("milkshake").cat(DrinkCategory.JUICE).vessel(Vessel.CUP).abv(0.00D)
			.nutrition(4).color(0xF5E8D8).fx(MobEffects.ABSORPTION, 60, 0).build());
	public static final DrinkDef HANGOVER_CURE = add(DrinkDef.builder("hangover_cure").cat(DrinkCategory.MEDICINE).vessel(Vessel.CUP)
			.abv(0.00D).caffeine(20.0D).sober(15.0D).relief(5.0D).cure().color(0xE8A82A)
			.fx(MobEffects.REGENERATION, 8, 0).build());
	public static final DrinkDef ASPIRIN = add(DrinkDef.builder("aspirin").cat(DrinkCategory.MEDICINE).vessel(Vessel.NONE).abv(0.00D)
			.sober(10.0D).relief(8.0D).cure().color(0xFFFFFF).build());

	private static DrinkDef add(DrinkDef def) {
		ALL.put(def.id(), def);
		return def;
	}

	public static Map<String, DrinkDef> all() {
		return Collections.unmodifiableMap(ALL);
	}

	public static DrinkDef get(String id) {
		return ALL.get(id);
	}

	private Drinks() {
	}
}
