modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "boozecraft"
version = "1.0.0"
displayName = "BoozeCraft"
authors = "s4fmer"
description = '''
fuckin pivo i vodka yoo im russian
created for sepiolSMP
'''

[[dependencies.boozecraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.boozecraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
