modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="vitalstages"
version="${version}"
displayName="вс"
authors="самса с пивом"
description='''оу вививи нахуй иди.'''
[[dependencies.vitalstages]]
modId="neoforge"
type="required"
versionRange="[21.1.233,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.vitalstages]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
[[mixins]]
config="vitalstages.mixins.json"
