package com.s4fmer.boozecraft.recipe;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;

/** GENERATED by tools/boozecraft_gen.py - bar counter mixing recipes. */
public final class MixRecipes {

	public static final class Entry {
		public final String result;
		public final int count;
		public final String[] inputs;

		Entry(String result, int count, String[] inputs) {
			this.result = result;
			this.count = count;
			this.inputs = inputs;
		}
	}

	private static final Map<String, Entry> ALL = new LinkedHashMap<>();

	static {
		add("boozecraft:rum_cola", 1, "boozecraft:rum", "boozecraft:cola");
		add("boozecraft:whiskey_cola", 1, "boozecraft:whiskey", "boozecraft:cola");
		add("boozecraft:vodka_energy", 1, "boozecraft:vodka", "boozecraft:energy_classic");
		add("boozecraft:vodka_energy", 1, "boozecraft:vodka", "boozecraft:energy_white");
		add("boozecraft:screwdriver", 1, "boozecraft:vodka", "boozecraft:orange_juice");
		add("boozecraft:gin_tonic", 1, "boozecraft:gin", "boozecraft:soda_water");
		add("boozecraft:mojito", 1, "boozecraft:white_rum", "boozecraft:lemon_lime_soda");
		add("boozecraft:margarita", 1, "boozecraft:tequila", "boozecraft:lemonade");
		add("boozecraft:black_russian", 1, "boozecraft:vodka", "boozecraft:espresso");
		add("boozecraft:irish_coffee", 1, "boozecraft:whiskey", "boozecraft:coffee");
		add("boozecraft:sangria", 1, "boozecraft:berry_wine", "boozecraft:orange_juice");
		add("boozecraft:berry_daiquiri", 1, "boozecraft:white_rum", "boozecraft:berry_juice");
		add("boozecraft:absinthe_bomb", 1, "boozecraft:absinthe", "boozecraft:energy_white");
		add("boozecraft:moonshine_punch", 1, "boozecraft:moonshine", "boozecraft:apple_juice", "boozecraft:lemonade");
		add("boozecraft:long_island", 1, "boozecraft:vodka", "boozecraft:gin", "boozecraft:white_rum");
		add("boozecraft:tequila_sunrise", 1, "boozecraft:tequila", "boozecraft:orange_juice");
		add("boozecraft:dirty_swill", 1, "boozecraft:moonshine", "boozecraft:mushroom_ale");
		add("boozecraft:hangover_cure", 1, "boozecraft:coffee", "boozecraft:orange_juice");
		add("boozecraft:hangover_cure", 1, "boozecraft:milkshake", "boozecraft:espresso");
	}

	private static void add(String result, int count, String... inputs) {
		ALL.put(key(inputs), new Entry(result, count, inputs));
	}

	private static String key(String[] ids) {
		String[] copy = ids.clone();
		Arrays.sort(copy);
		return String.join("+", copy);
	}

	public static Entry find(List<String> ids) {
		return ALL.get(key(ids.toArray(new String[0])));
	}

	public static Collection<Entry> all() {
		return new ArrayList<>(ALL.values());
	}

	public static Item item(String id) {
		return BuiltInRegistries.ITEM.getOptional(ResourceLocation.parse(id)).orElse(null);
	}

	private MixRecipes() {
	}
}
