package com.s4fmer.boozecraft.recipe;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.s4fmer.boozecraft.block.ProcessorType;
import net.minecraft.core.NonNullList;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;

/** GENERATED by tools/boozecraft_gen.py - fermenter / still / aging barrel recipes. */
public final class ProcessRecipes {

	public static final class Entry {
		public final ProcessorType type;
		public final String[] inputs;
		public final String result;
		public final int count;
		public final int time;

		Entry(ProcessorType type, String result, int count, int time, String[] inputs) {
			this.type = type;
			this.result = result;
			this.count = count;
			this.time = time;
			this.inputs = inputs;
		}
	}

	private static final List<Entry> ALL = new ArrayList<>();

	static {
		add(ProcessorType.FERMENTER, "boozecraft:beer_light", 2, 1200, "boozecraft:mash_grain", "boozecraft:mug", "boozecraft:mug");
		add(ProcessorType.FERMENTER, "boozecraft:beer_dark", 2, 1400, "boozecraft:mash_grain", "minecraft:cocoa_beans", "boozecraft:mug", "boozecraft:mug");
		add(ProcessorType.FERMENTER, "boozecraft:cider", 2, 1200, "boozecraft:mash_fruit", "boozecraft:mug", "boozecraft:mug");
		add(ProcessorType.FERMENTER, "boozecraft:mead", 2, 1800, "boozecraft:mash_honey", "boozecraft:mug", "boozecraft:mug");
		add(ProcessorType.FERMENTER, "boozecraft:braga", 2, 1000, "boozecraft:mash_sugar", "boozecraft:mug", "boozecraft:mug");
		add(ProcessorType.FERMENTER, "boozecraft:potato_brew", 2, 1200, "boozecraft:mash_potato", "boozecraft:mug", "boozecraft:mug");
		add(ProcessorType.FERMENTER, "boozecraft:mushroom_ale", 2, 1600, "boozecraft:mash_mushroom", "boozecraft:mug", "boozecraft:mug");
		add(ProcessorType.FERMENTER, "boozecraft:pumpkin_ale", 2, 1400, "boozecraft:mash_pumpkin", "boozecraft:mug", "boozecraft:mug");
		add(ProcessorType.FERMENTER, "boozecraft:berry_wine", 2, 2000, "boozecraft:mash_berry", "minecraft:glass_bottle", "minecraft:glass_bottle");
		add(ProcessorType.FERMENTER, "boozecraft:melon_wine", 2, 1800, "boozecraft:mash_melon", "minecraft:glass_bottle", "minecraft:glass_bottle");
		add(ProcessorType.FERMENTER, "boozecraft:cactus_wine", 2, 2000, "boozecraft:mash_cactus", "minecraft:glass_bottle", "minecraft:glass_bottle");
		add(ProcessorType.FERMENTER, "boozecraft:chorus_wine", 2, 2400, "boozecraft:mash_chorus", "minecraft:glass_bottle", "minecraft:glass_bottle");
		add(ProcessorType.FERMENTER, "boozecraft:glow_wine", 2, 2200, "boozecraft:mash_glow", "minecraft:glass_bottle", "minecraft:glass_bottle");
		add(ProcessorType.FERMENTER, "boozecraft:sake", 2, 2600, "boozecraft:mash_grain", "boozecraft:mash_grain", "minecraft:glass_bottle", "minecraft:glass_bottle");
		add(ProcessorType.STILL, "boozecraft:moonshine", 1, 800, "boozecraft:braga", "minecraft:glass_bottle");
		add(ProcessorType.STILL, "boozecraft:vodka", 1, 900, "boozecraft:potato_brew", "minecraft:glass_bottle");
		add(ProcessorType.STILL, "boozecraft:white_rum", 1, 900, "boozecraft:mash_sugar", "minecraft:glass_bottle");
		add(ProcessorType.STILL, "boozecraft:brandy", 1, 1000, "boozecraft:cider", "minecraft:glass_bottle");
		add(ProcessorType.STILL, "boozecraft:schnapps", 1, 900, "boozecraft:mash_fruit", "minecraft:glass_bottle");
		add(ProcessorType.STILL, "boozecraft:tequila", 1, 1000, "boozecraft:mash_cactus", "minecraft:glass_bottle");
		add(ProcessorType.STILL, "boozecraft:gin", 1, 1000, "boozecraft:moonshine", "minecraft:sweet_berries");
		add(ProcessorType.STILL, "boozecraft:absinthe", 1, 1200, "boozecraft:moonshine", "minecraft:fern");
		add(ProcessorType.STILL, "boozecraft:sambuca", 1, 1100, "boozecraft:moonshine", "minecraft:glow_berries", "boozecraft:shot_glass");
		add(ProcessorType.STILL, "boozecraft:dragon_absinthe", 1, 1600, "boozecraft:absinthe", "minecraft:dragon_breath");
		add(ProcessorType.STILL, "boozecraft:nether_whiskey", 1, 1400, "boozecraft:whiskey", "minecraft:blaze_powder");
		add(ProcessorType.STILL, "boozecraft:everclear", 1, 1200, "boozecraft:moonshine", "boozecraft:moonshine");
		add(ProcessorType.AGING, "boozecraft:whiskey", 1, 2400, "boozecraft:moonshine");
		add(ProcessorType.AGING, "boozecraft:rum", 1, 2400, "boozecraft:white_rum");
		add(ProcessorType.AGING, "boozecraft:cognac", 1, 3000, "boozecraft:brandy");
		add(ProcessorType.AGING, "boozecraft:sake", 1, 2000, "boozecraft:braga", "minecraft:glass_bottle");
		ALL.sort((a, b) -> Integer.compare(b.inputs.length, a.inputs.length));
	}

	private static void add(ProcessorType type, String result, int count, int time, String... inputs) {
		ALL.add(new Entry(type, result, count, time, inputs));
	}

	public static List<Entry> all() {
		return ALL;
	}

	public static Item item(String id) {
		return BuiltInRegistries.ITEM.getOptional(ResourceLocation.parse(id)).orElse(null);
	}

	/** Finds a recipe whose ingredients are all present and where nothing foreign is inside. */
	public static Entry find(ProcessorType type, NonNullList<ItemStack> items, int inputSlots) {
		Map<Item, Integer> have = new HashMap<>();
		int total = 0;
		for (int i = 0; i < inputSlots; i++) {
			ItemStack stack = items.get(i);
			if (!stack.isEmpty()) {
				have.merge(stack.getItem(), stack.getCount(), Integer::sum);
				total += stack.getCount();
			}
		}
		if (total == 0) {
			return null;
		}
		outer:
		for (Entry entry : ALL) {
			if (entry.type != type) {
				continue;
			}
			Map<Item, Integer> need = new HashMap<>();
			for (String id : entry.inputs) {
				Item item = item(id);
				if (item == null) {
					continue outer;
				}
				need.merge(item, 1, Integer::sum);
			}
			for (Map.Entry<Item, Integer> requirement : need.entrySet()) {
				Integer got = have.get(requirement.getKey());
				if (got == null || got.intValue() < requirement.getValue().intValue()) {
					continue outer;
				}
			}
			for (Item present : have.keySet()) {
				if (!need.containsKey(present)) {
					continue outer;
				}
			}
			return entry;
		}
		return null;
	}

	public static void consume(Entry entry, NonNullList<ItemStack> items, int inputSlots) {
		for (String id : entry.inputs) {
			Item item = item(id);
			if (item == null) {
				continue;
			}
			for (int i = 0; i < inputSlots; i++) {
				ItemStack stack = items.get(i);
				if (!stack.isEmpty() && stack.getItem() == item) {
					stack.shrink(1);
					break;
				}
			}
		}
	}

	private ProcessRecipes() {
	}
}
