# -*- coding: utf-8 -*-
"""BoozeCraft content tables. Single source of truth for Java, JSON, lang, textures and docs."""

# cat:     SPIRIT BEER WINE COCKTAIL MASH SODA ENERGY COFFEE JUICE MEDICINE
# vessel:  BOTTLE CUP MUG CAN SHOT NONE
# tex:     bottle can cup mug shot jar pill
# fx:      list of (MobEffects field, seconds, amplifier)

D = lambda **kw: kw

DRINKS = [
    # ---------------------------------------------------------------- mashes
    D(id="mash_grain", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0xC9B37A, stack=16,
      en="Grain Mash", ru="Зерновая закваска", fx=[]),
    D(id="mash_potato", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0xD8C9A0, stack=16,
      en="Potato Mash", ru="Картофельная закваска", fx=[]),
    D(id="mash_sugar", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0xF0EAD8, stack=16,
      en="Sugar Mash", ru="Сахарная закваска", fx=[]),
    D(id="mash_fruit", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0xC8D86A, stack=16,
      en="Apple Mash", ru="Яблочная закваска", fx=[]),
    D(id="mash_berry", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0x9B2A4A, stack=16,
      en="Berry Mash", ru="Ягодная закваска", fx=[]),
    D(id="mash_melon", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0xE85A5A, stack=16,
      en="Melon Mash", ru="Арбузная закваска", fx=[]),
    D(id="mash_cactus", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0x4A8A2A, stack=16,
      en="Cactus Mash", ru="Кактусовая закваска", fx=[]),
    D(id="mash_honey", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0xE0A82A, stack=16,
      en="Honey Mash", ru="Медовая закваска", fx=[]),
    D(id="mash_mushroom", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0x8B6A4A, stack=16,
      en="Mushroom Mash", ru="Грибная закваска", fx=[]),
    D(id="mash_chorus", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0x9B5AC9, stack=16,
      en="Chorus Mash", ru="Хорусовая закваска", fx=[]),
    D(id="mash_glow", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0xE8D84A, stack=16,
      en="Glow Berry Mash", ru="Светящаяся закваска", fx=[]),
    D(id="mash_pumpkin", cat="MASH", vessel="NONE", abv=0.0, tex="jar", color=0xE08A2A, stack=16,
      en="Pumpkin Mash", ru="Тыквенная закваска", fx=[]),

    # ------------------------------------------------------- fermented drinks
    D(id="beer_light", cat="BEER", vessel="MUG", abv=0.05, nutrition=1, tex="mug", color=0xE9B44C, stack=16,
      en="Light Beer", ru="Светлое пиво", fx=[("MOVEMENT_SPEED", 20, 0)]),
    D(id="beer_dark", cat="BEER", vessel="MUG", abv=0.06, nutrition=2, tex="mug", color=0x6B3A10, stack=16,
      en="Dark Beer", ru="Тёмное пиво", fx=[("DIG_SPEED", 25, 0)]),
    D(id="cider", cat="BEER", vessel="MUG", abv=0.06, nutrition=2, tex="mug", color=0xD9A72A, stack=16,
      en="Apple Cider", ru="Яблочный сидр", fx=[("REGENERATION", 8, 0)]),
    D(id="mead", cat="WINE", vessel="MUG", abv=0.12, nutrition=2, tex="mug", color=0xE0A32E, stack=16,
      en="Mead", ru="Медовуха", fx=[("REGENERATION", 10, 0), ("ABSORPTION", 60, 0)]),
    D(id="braga", cat="BEER", vessel="MUG", abv=0.09, nutrition=1, tex="mug", color=0xC9B37A, stack=16,
      en="Braga", ru="Брага", fx=[("MOVEMENT_SPEED", 15, 0)]),
    D(id="potato_brew", cat="BEER", vessel="MUG", abv=0.07, nutrition=2, tex="mug", color=0xD8C9A0, stack=16,
      en="Potato Brew", ru="Картофельная бражка", fx=[("DIG_SPEED", 20, 0)]),
    D(id="mushroom_ale", cat="BEER", vessel="MUG", abv=0.08, nutrition=1, tex="mug", color=0x8B6A4A, stack=16,
      en="Mushroom Ale", ru="Грибной эль", fx=[("NIGHT_VISION", 30, 0)]),
    D(id="pumpkin_ale", cat="BEER", vessel="MUG", abv=0.07, nutrition=2, tex="mug", color=0xE08A2A, stack=16,
      en="Pumpkin Ale", ru="Тыквенный эль", fx=[("ABSORPTION", 45, 0)]),
    D(id="berry_wine", cat="WINE", vessel="BOTTLE", abv=0.13, nutrition=1, tex="bottle", color=0x7A1030, stack=16,
      en="Berry Wine", ru="Ягодное вино", fx=[("LUCK", 60, 0)]),
    D(id="melon_wine", cat="WINE", vessel="BOTTLE", abv=0.11, nutrition=1, tex="bottle", color=0xE05A5A, stack=16,
      en="Melon Wine", ru="Арбузное вино", fx=[("REGENERATION", 6, 1)]),
    D(id="cactus_wine", cat="WINE", vessel="BOTTLE", abv=0.12, tex="bottle", color=0x5A9E3A, stack=16,
      en="Cactus Wine", ru="Кактусовое вино", fx=[("DAMAGE_RESISTANCE", 30, 0)]),
    D(id="chorus_wine", cat="WINE", vessel="BOTTLE", abv=0.14, tex="bottle", color=0xA36BC9, stack=16,
      en="Chorus Wine", ru="Хорусовое вино", fx=[("SLOW_FALLING", 30, 0)]),
    D(id="glow_wine", cat="WINE", vessel="BOTTLE", abv=0.13, tex="bottle", color=0xE8E45A, stack=16,
      en="Glowing Wine", ru="Светящееся вино", fx=[("GLOWING", 45, 0), ("NIGHT_VISION", 30, 0)]),
    D(id="sake", cat="WINE", vessel="BOTTLE", abv=0.16, nutrition=1, tex="bottle", color=0xF2F2E0, stack=16,
      en="Sake", ru="Саке", fx=[("DAMAGE_BOOST", 40, 0)]),

    # ---------------------------------------------------------------- spirits
    D(id="moonshine", cat="SPIRIT", vessel="BOTTLE", abv=0.45, tex="bottle", color=0xF0F0E8, stack=16,
      en="Moonshine", ru="Самогон", fx=[("DAMAGE_BOOST", 30, 0)]),
    D(id="vodka", cat="SPIRIT", vessel="BOTTLE", abv=0.40, tex="bottle", color=0xEAF6FF, stack=16,
      en="Vodka", ru="Водка", fx=[("DAMAGE_BOOST", 45, 0), ("FIRE_RESISTANCE", 20, 0)]),
    D(id="white_rum", cat="SPIRIT", vessel="BOTTLE", abv=0.38, tex="bottle", color=0xF5EFD8, stack=16,
      en="White Rum", ru="Белый ром", fx=[("MOVEMENT_SPEED", 45, 0)]),
    D(id="rum", cat="SPIRIT", vessel="BOTTLE", abv=0.40, tex="bottle", color=0x8A4A18, stack=16,
      en="Dark Rum", ru="Тёмный ром", fx=[("MOVEMENT_SPEED", 60, 0), ("DAMAGE_BOOST", 30, 0)]),
    D(id="whiskey", cat="SPIRIT", vessel="BOTTLE", abv=0.43, tex="bottle", color=0xC1651A, stack=16,
      en="Whiskey", ru="Виски", fx=[("DAMAGE_RESISTANCE", 45, 0), ("DAMAGE_BOOST", 30, 0)]),
    D(id="nether_whiskey", cat="SPIRIT", vessel="BOTTLE", abv=0.55, tex="bottle", color=0xE03A10, stack=16,
      en="Nether Fire Whiskey", ru="Адское виски", fx=[("FIRE_RESISTANCE", 180, 0), ("DAMAGE_BOOST", 45, 1)]),
    D(id="brandy", cat="SPIRIT", vessel="BOTTLE", abv=0.40, tex="bottle", color=0xA8541A, stack=16,
      en="Brandy", ru="Брэнди", fx=[("REGENERATION", 10, 0), ("DAMAGE_RESISTANCE", 30, 0)]),
    D(id="cognac", cat="SPIRIT", vessel="BOTTLE", abv=0.42, tex="bottle", color=0x8F3F12, stack=16,
      en="Cognac", ru="Коньяк", fx=[("REGENERATION", 12, 1), ("LUCK", 120, 0)]),
    D(id="tequila", cat="SPIRIT", vessel="BOTTLE", abv=0.38, tex="bottle", color=0xEFE39A, stack=16,
      en="Tequila", ru="Текила", fx=[("MOVEMENT_SPEED", 60, 1)]),
    D(id="gin", cat="SPIRIT", vessel="BOTTLE", abv=0.40, tex="bottle", color=0xE6F2E8, stack=16,
      en="Gin", ru="Джин", fx=[("WATER_BREATHING", 60, 0), ("DOLPHINS_GRACE", 30, 0)]),
    D(id="absinthe", cat="SPIRIT", vessel="BOTTLE", abv=0.60, tex="bottle", color=0x7ADB3A, stack=16,
      en="Absinthe", ru="Абсент", fx=[("NIGHT_VISION", 120, 0), ("JUMP", 60, 1)]),
    D(id="dragon_absinthe", cat="SPIRIT", vessel="BOTTLE", abv=0.70, tex="bottle", color=0x35E0B0, stack=16,
      en="Dragon Absinthe", ru="Драконий абсент",
      fx=[("NIGHT_VISION", 180, 0), ("SLOW_FALLING", 60, 0), ("REGENERATION", 10, 1)]),
    D(id="schnapps", cat="SPIRIT", vessel="BOTTLE", abv=0.35, tex="bottle", color=0xEFE0C0, stack=16,
      en="Schnapps", ru="Шнапс", fx=[("JUMP", 45, 0)]),
    D(id="sambuca", cat="SPIRIT", vessel="SHOT", abv=0.38, tex="shot", color=0xF0EAD0, stack=16,
      en="Sambuca", ru="Самбука", fx=[("DIG_SPEED", 45, 1)]),
    D(id="everclear", cat="SPIRIT", vessel="BOTTLE", abv=0.75, tex="bottle", color=0xFFFFFF, stack=16,
      en="Everclear", ru="Спирт", fx=[("DAMAGE_BOOST", 60, 1), ("FIRE_RESISTANCE", 30, 0)]),

    # -------------------------------------------------------------- cocktails
    D(id="rum_cola", cat="COCKTAIL", vessel="CUP", abv=0.14, caffeine=15, tex="cup", color=0x4A2410, stack=16,
      en="Rum & Cola", ru="Ром-кола", fx=[("MOVEMENT_SPEED", 60, 0)]),
    D(id="whiskey_cola", cat="COCKTAIL", vessel="CUP", abv=0.15, caffeine=15, tex="cup", color=0x5A2A10, stack=16,
      en="Whiskey & Cola", ru="Виски-кола", fx=[("DAMAGE_RESISTANCE", 60, 0)]),
    D(id="vodka_energy", cat="COCKTAIL", vessel="CUP", abv=0.16, caffeine=40, tex="cup", color=0x9BE03A, stack=16,
      en="Vodka Energy", ru="Водка-энергетик", fx=[("MOVEMENT_SPEED", 90, 1), ("DIG_SPEED", 90, 0)]),
    D(id="screwdriver", cat="COCKTAIL", vessel="CUP", abv=0.14, nutrition=1, tex="cup", color=0xF29A1A, stack=16,
      en="Screwdriver", ru="Отвёртка", fx=[("REGENERATION", 8, 0)]),
    D(id="gin_tonic", cat="COCKTAIL", vessel="CUP", abv=0.13, tex="cup", color=0xDFF3E0, stack=16,
      en="Gin & Tonic", ru="Джин-тоник", fx=[("WATER_BREATHING", 90, 0)]),
    D(id="mojito", cat="COCKTAIL", vessel="CUP", abv=0.12, tex="cup", color=0xB9E86A, stack=16,
      en="Mojito", ru="Мохито", fx=[("MOVEMENT_SPEED", 60, 0), ("JUMP", 45, 0)]),
    D(id="margarita", cat="COCKTAIL", vessel="CUP", abv=0.15, tex="cup", color=0xE8F0A0, stack=16,
      en="Margarita", ru="Маргарита", fx=[("LUCK", 90, 0)]),
    D(id="black_russian", cat="COCKTAIL", vessel="SHOT", abv=0.22, caffeine=30, tex="shot", color=0x2A1A10, stack=16,
      en="Black Russian", ru="Чёрный русский", fx=[("DIG_SPEED", 60, 1)]),
    D(id="irish_coffee", cat="COCKTAIL", vessel="MUG", abv=0.18, caffeine=35, tex="mug", color=0x6B4426, stack=16,
      en="Irish Coffee", ru="Айриш кофе", fx=[("DAMAGE_RESISTANCE", 60, 0)]),
    D(id="sangria", cat="COCKTAIL", vessel="CUP", abv=0.11, nutrition=1, tex="cup", color=0x9B1A3A, stack=16,
      en="Sangria", ru="Сангрия", fx=[("LUCK", 120, 0), ("REGENERATION", 8, 0)]),
    D(id="berry_daiquiri", cat="COCKTAIL", vessel="CUP", abv=0.15, nutrition=1, tex="cup", color=0xD84A7A, stack=16,
      en="Berry Daiquiri", ru="Ягодный дайкири", fx=[("LUCK", 60, 0), ("MOVEMENT_SPEED", 45, 0)]),
    D(id="absinthe_bomb", cat="COCKTAIL", vessel="SHOT", abv=0.30, caffeine=45, tex="shot", color=0x8AF04A, stack=16,
      en="Absinthe Bomb", ru="Абсент-бомба", fx=[("NIGHT_VISION", 120, 0), ("JUMP", 60, 1)]),
    D(id="moonshine_punch", cat="COCKTAIL", vessel="CUP", abv=0.20, nutrition=1, tex="cup", color=0xF2C24A, stack=16,
      en="Moonshine Punch", ru="Самогонный пунш", fx=[("DAMAGE_BOOST", 60, 1), ("MOVEMENT_SPEED", 60, 0)]),
    D(id="long_island", cat="COCKTAIL", vessel="CUP", abv=0.32, tex="cup", color=0xB06A2A, stack=16,
      en="Long Island", ru="Лонг-Айленд", fx=[("DAMAGE_BOOST", 90, 1), ("MOVEMENT_SPEED", 90, 0)]),
    D(id="tequila_sunrise", cat="COCKTAIL", vessel="CUP", abv=0.14, nutrition=1, tex="cup", color=0xF06A2A, stack=16,
      en="Tequila Sunrise", ru="Текила санрайз", fx=[("MOVEMENT_SPEED", 90, 1)]),
    D(id="dirty_swill", cat="COCKTAIL", vessel="MUG", abv=0.35, tex="mug", color=0x6A5A3A, stack=16,
      en="Dirty Swill", ru="Мутное пойло", fx=[("HUNGER", 30, 0), ("POISON", 5, 0)]),
    D(id="hangover_cure", cat="MEDICINE", vessel="CUP", abv=0.0, caffeine=20, sober=15, relief=5, cure=True,
      tex="cup", color=0xE8A82A, stack=16, en="Hangover Cure", ru="Антипохмелин",
      fx=[("REGENERATION", 8, 0)]),

    # ------------------------------------------------------------ soft drinks
    D(id="cola", cat="SODA", vessel="CAN", abv=0.0, caffeine=12, nutrition=1, tex="can", color=0x2A1408,
      accent=0xE02A2A, stack=16, en="Cola", ru="Кола", fx=[("MOVEMENT_SPEED", 30, 0)]),
    D(id="orange_soda", cat="SODA", vessel="CAN", abv=0.0, nutrition=1, tex="can", color=0xF08A10,
      accent=0xFFD24A, stack=16, en="Orange Soda", ru="Апельсиновая газировка", fx=[]),
    D(id="lemon_lime_soda", cat="SODA", vessel="CAN", abv=0.0, nutrition=1, tex="can", color=0xC8E85A,
      accent=0x4ADB6A, stack=16, en="Lemon-Lime Soda", ru="Лимон-лайм газировка", fx=[]),
    D(id="soda_water", cat="SODA", vessel="BOTTLE", abv=0.0, sober=2, tex="bottle", color=0xDCEFF7, stack=16,
      en="Soda Water", ru="Газированная вода", fx=[]),
    D(id="energy_classic", cat="ENERGY", vessel="CAN", abv=0.0, caffeine=45, tex="can", color=0x121212,
      accent=0x8BE03A, stack=16, en="Monster Energy Classic", ru="Энергетик «Монстр» классический",
      fx=[("MOVEMENT_SPEED", 90, 0), ("DIG_SPEED", 60, 0)]),
    D(id="energy_white", cat="ENERGY", vessel="CAN", abv=0.0, caffeine=55, tex="can", color=0xF2F2F2,
      accent=0x39C3E0, stack=16, en="Monster Energy White", ru="Энергетик «Монстр» белый",
      fx=[("MOVEMENT_SPEED", 120, 0), ("JUMP", 60, 0)]),
    D(id="energy_mango", cat="ENERGY", vessel="CAN", abv=0.0, caffeine=40, nutrition=1, tex="can", color=0xF0B02A,
      accent=0xFFE45A, stack=16, en="Mango Energy", ru="Манговый энергетик",
      fx=[("MOVEMENT_SPEED", 90, 0)]),
    D(id="coffee", cat="COFFEE", vessel="MUG", abv=0.0, caffeine=35, sober=6, tex="mug", color=0x4A2A18, stack=16,
      en="Coffee", ru="Кофе", fx=[("DIG_SPEED", 60, 0)]),
    D(id="espresso", cat="COFFEE", vessel="SHOT", abv=0.0, caffeine=50, sober=10, tex="shot", color=0x2A1810, stack=16,
      en="Espresso", ru="Эспрессо", fx=[("DIG_SPEED", 90, 1)]),
    D(id="latte", cat="COFFEE", vessel="MUG", abv=0.0, caffeine=30, sober=5, nutrition=2, tex="mug", color=0xC9A882,
      stack=16, en="Latte", ru="Латте", fx=[("MOVEMENT_SPEED", 45, 0)]),
    D(id="hot_cocoa", cat="COFFEE", vessel="MUG", abv=0.0, nutrition=3, tex="mug", color=0x6B4426, stack=16,
      en="Hot Cocoa", ru="Горячий шоколад", fx=[("REGENERATION", 6, 0)]),
    D(id="sweet_tea", cat="COFFEE", vessel="MUG", abv=0.0, caffeine=12, nutrition=1, relief=3, tex="mug",
      color=0xC98A3A, stack=16, en="Sweet Tea", ru="Сладкий чай", fx=[]),
    D(id="apple_juice", cat="JUICE", vessel="CUP", abv=0.0, nutrition=2, tex="cup", color=0xE8C24A, stack=16,
      en="Apple Juice", ru="Яблочный сок", fx=[]),
    D(id="orange_juice", cat="JUICE", vessel="CUP", abv=0.0, nutrition=2, tex="cup", color=0xF0921A, stack=16,
      en="Orange Juice", ru="Апельсиновый сок", fx=[("NIGHT_VISION", 20, 0)]),
    D(id="berry_juice", cat="JUICE", vessel="CUP", abv=0.0, nutrition=2, tex="cup", color=0xC02A5A, stack=16,
      en="Berry Juice", ru="Ягодный сок", fx=[]),
    D(id="melon_juice", cat="JUICE", vessel="CUP", abv=0.0, nutrition=2, tex="cup", color=0xF06A6A, stack=16,
      en="Melon Juice", ru="Арбузный сок", fx=[]),
    D(id="lemonade", cat="JUICE", vessel="CUP", abv=0.0, nutrition=1, sober=3, tex="cup", color=0xF2E86A, stack=16,
      en="Lemonade", ru="Лимонад", fx=[]),
    D(id="milkshake", cat="JUICE", vessel="CUP", abv=0.0, nutrition=4, tex="cup", color=0xF5E8D8, stack=16,
      en="Milkshake", ru="Молочный коктейль", fx=[("ABSORPTION", 60, 0)]),

    # ---------------------------------------------------------------- medicine
    D(id="aspirin", cat="MEDICINE", vessel="NONE", abv=0.0, sober=10, relief=8, cure=True, tex="pill",
      color=0xFFFFFF, stack=16, en="Aspirin", ru="Аспирин", fx=[]),
]

# ---------------------------------------------------------------------------
# Plain items (not drinkable)
# ---------------------------------------------------------------------------
TOOLS = [
    D(id="glass_cup", en="Glass", ru="Стакан", tex="cup_empty", stack=16, cls="Item"),
    D(id="mug", en="Beer Mug", ru="Пивная кружка", tex="mug_empty", stack=16, cls="Item"),
    D(id="shot_glass", en="Shot Glass", ru="Рюмка", tex="shot_empty", stack=16, cls="Item"),
    D(id="empty_can", en="Empty Can", ru="Пустая банка", tex="can_empty", stack=64, cls="Item"),
    D(id="shaker", en="Cocktail Shaker", ru="Шейкер", tex="shaker", stack=1, cls="ShakerItem"),
    D(id="coffee_beans", en="Coffee Beans", ru="Кофейные зёрна", tex="beans", stack=64, cls="Item"),
    D(id="yeast", en="Yeast", ru="Дрожжи", tex="powder", stack=64, cls="Item"),
    D(id="soda_syrup", en="Soda Syrup", ru="Сироп для газировки", tex="syrup_soda", stack=16, cls="Item"),
    D(id="energy_syrup", en="Energy Syrup", ru="Энергетический сироп", tex="syrup_energy", stack=16, cls="Item"),
]

# ---------------------------------------------------------------------------
# Blocks
# ---------------------------------------------------------------------------
BLOCKS = [
    D(id="fermenter", en="Fermenter", ru="Бродильная бочка", tool="axe", top=0xB07A3A, side=0x8A5A28, band=0xC87A3A),
    D(id="still", en="Copper Still", ru="Самогонный аппарат", tool="pickaxe", top=0xE07A4A, side=0xC1602A, band=0x8A3A18),
    D(id="aging_barrel", en="Aging Barrel", ru="Бочка для выдержки", tool="axe", top=0x6A4526, side=0x53341C, band=0x9A9A9A),
    D(id="bar_counter", en="Bar Counter", ru="Барная стойка", tool="axe", top=0x7A4A22, side=0x5A3418, band=0xC8A050),
]

# ---------------------------------------------------------------------------
# Custom mob effects
# ---------------------------------------------------------------------------
EFFECTS = [
    D(id="tipsy", en="Tipsy", ru="Навеселе", color=0xE0B34C),
    D(id="drunk", en="Drunk", ru="Опьянение", color=0xA9662B),
    D(id="heavy_drunk", en="Heavy Drunk", ru="Сильное опьянение", color=0x6B3A15),
    D(id="passed_out", en="Passed Out", ru="Вырубило", color=0x2B2B2B),
    D(id="hangover", en="Hangover", ru="Похмелье", color=0x7F8C8D),
    D(id="withdrawal", en="Withdrawal", ru="Абстиненция", color=0x6C3FA0),
    D(id="caffeine", en="Caffeine Rush", ru="Кофеин", color=0x6F4E37),
    D(id="jitters", en="Jitters", ru="Кофеиновый тремор", color=0xD2691E),
]

# ---------------------------------------------------------------------------
# Crafting table / furnace recipes
# ---------------------------------------------------------------------------
B = "boozecraft:"
M = "minecraft:"

CRAFTS = [
    # tools ------------------------------------------------------------------
    D(kind="shaped", result=B + "glass_cup", count=2, pattern=["G G", " G "], key={"G": M + "glass_pane"}),
    D(kind="shaped", result=B + "mug", count=2, pattern=["GN", "GG"], key={"G": M + "glass_pane", "N": M + "iron_nugget"}),
    D(kind="shaped", result=B + "shot_glass", count=2, pattern=["GG"], key={"G": M + "glass_pane"}),
    D(kind="shapeless", result=B + "empty_can", count=3, ingredients=[M + "iron_nugget"] * 3),
    D(kind="shaped", result=B + "shaker", count=1, pattern=[" I ", "I I", " I "], key={"I": M + "iron_ingot"}),
    D(kind="shapeless", result=B + "yeast", count=3,
      ingredients=[M + "sugar", M + "wheat", M + "brown_mushroom"]),
    D(kind="shapeless", result=B + "soda_syrup", count=2,
      ingredients=[M + "sugar", M + "sugar", M + "cocoa_beans"]),
    D(kind="shapeless", result=B + "energy_syrup", count=2,
      ingredients=[M + "sugar", M + "sugar", M + "glow_berries", B + "coffee_beans"]),
    D(kind="shapeless", result=B + "aspirin", count=2,
      ingredients=[M + "bone_meal", M + "sugar", M + "glow_berries"]),
    D(kind="smelting", result=B + "coffee_beans", count=1, ingredient=M + "cocoa_beans", exp=0.1, time=200),
    D(kind="smelting", result=M + "iron_nugget", count=1, ingredient=B + "empty_can", exp=0.05, time=200,
      name="empty_can_recycling"),

    # blocks -----------------------------------------------------------------
    D(kind="shaped", result=B + "fermenter", count=1, pattern=[" C ", "CBC", " C "],
      key={"C": M + "copper_ingot", "B": M + "barrel"}),
    D(kind="shaped", result=B + "still", count=1, pattern=[" C ", "CBC", "III"],
      key={"C": M + "copper_ingot", "B": M + "bucket", "I": M + "iron_ingot"}),
    D(kind="shaped", result=B + "aging_barrel", count=1, pattern=[" I ", "PBP", " P "],
      key={"P": M + "oak_planks", "B": M + "barrel", "I": M + "iron_ingot"}),
    D(kind="shaped", result=B + "bar_counter", count=2, pattern=["SSS", "PPP"],
      key={"S": M + "oak_slab", "P": M + "oak_planks"}),

    # mashes -----------------------------------------------------------------
    D(kind="shapeless", result=B + "mash_grain", count=1,
      ingredients=[M + "wheat"] * 3 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_potato", count=1,
      ingredients=[M + "potato"] * 3 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_sugar", count=1,
      ingredients=[M + "sugar"] * 3 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_fruit", count=1,
      ingredients=[M + "apple"] * 2 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_berry", count=1,
      ingredients=[M + "sweet_berries"] * 3 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_melon", count=1,
      ingredients=[M + "melon_slice"] * 3 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_cactus", count=1,
      ingredients=[M + "cactus"] * 2 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_honey", count=1,
      ingredients=[M + "honey_bottle", M + "sugar", B + "yeast"]),
    D(kind="shapeless", result=B + "mash_mushroom", count=1,
      ingredients=[M + "brown_mushroom", M + "red_mushroom", B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_chorus", count=1,
      ingredients=[M + "chorus_fruit"] * 2 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_glow", count=1,
      ingredients=[M + "glow_berries"] * 3 + [B + "yeast", M + "water_bucket"]),
    D(kind="shapeless", result=B + "mash_pumpkin", count=1,
      ingredients=[M + "pumpkin", B + "yeast", M + "water_bucket"]),

    # soft drinks ------------------------------------------------------------
    D(kind="shapeless", result=B + "cola", count=2,
      ingredients=[B + "soda_syrup", M + "sugar", B + "empty_can", B + "empty_can", M + "water_bucket"]),
    D(kind="shapeless", result=B + "orange_soda", count=2,
      ingredients=[B + "soda_syrup", M + "carrot", M + "sugar", B + "empty_can", B + "empty_can", M + "water_bucket"]),
    D(kind="shapeless", result=B + "lemon_lime_soda", count=2,
      ingredients=[B + "soda_syrup", M + "glow_berries", B + "empty_can", B + "empty_can", M + "water_bucket"]),
    D(kind="shapeless", result=B + "energy_classic", count=2,
      ingredients=[B + "energy_syrup", M + "sugar", B + "empty_can", B + "empty_can", M + "water_bucket"]),
    D(kind="shapeless", result=B + "energy_white", count=2,
      ingredients=[B + "energy_syrup", M + "sugar", M + "glowstone_dust", B + "empty_can", B + "empty_can",
                   M + "water_bucket"]),
    D(kind="shapeless", result=B + "energy_mango", count=2,
      ingredients=[B + "energy_syrup", M + "glow_berries", M + "sugar", B + "empty_can", B + "empty_can",
                   M + "water_bucket"]),
    D(kind="shapeless", result=B + "coffee", count=2,
      ingredients=[B + "coffee_beans", B + "mug", B + "mug", M + "water_bucket"]),
    D(kind="shapeless", result=B + "espresso", count=2,
      ingredients=[B + "coffee_beans", B + "coffee_beans", B + "shot_glass", B + "shot_glass", M + "water_bucket"]),
    D(kind="shapeless", result=B + "latte", count=2,
      ingredients=[B + "coffee_beans", M + "milk_bucket", B + "mug", B + "mug"]),
    D(kind="shapeless", result=B + "hot_cocoa", count=2,
      ingredients=[M + "cocoa_beans", M + "milk_bucket", M + "sugar", B + "mug", B + "mug"]),
    D(kind="shapeless", result=B + "sweet_tea", count=2,
      ingredients=[M + "dried_kelp", M + "sugar", B + "mug", B + "mug", M + "water_bucket"]),
    D(kind="shapeless", result=B + "apple_juice", count=2,
      ingredients=[M + "apple", M + "apple", M + "sugar", B + "glass_cup", B + "glass_cup"]),
    D(kind="shapeless", result=B + "orange_juice", count=2,
      ingredients=[M + "carrot", M + "carrot", M + "sugar", B + "glass_cup", B + "glass_cup"]),
    D(kind="shapeless", result=B + "berry_juice", count=2,
      ingredients=[M + "sweet_berries"] * 3 + [M + "sugar", B + "glass_cup", B + "glass_cup"]),
    D(kind="shapeless", result=B + "melon_juice", count=2,
      ingredients=[M + "melon_slice"] * 3 + [B + "glass_cup", B + "glass_cup"]),
    D(kind="shapeless", result=B + "lemonade", count=2,
      ingredients=[M + "sugar", M + "sugar", M + "glow_berries", B + "glass_cup", B + "glass_cup",
                   M + "water_bucket"]),
    D(kind="shapeless", result=B + "milkshake", count=2,
      ingredients=[M + "milk_bucket", M + "sugar", M + "cocoa_beans", B + "glass_cup", B + "glass_cup"]),
    D(kind="shapeless", result=B + "soda_water", count=2,
      ingredients=[M + "glass_bottle", M + "glass_bottle", M + "gunpowder", M + "water_bucket"]),
]

# ---------------------------------------------------------------------------
# Machine recipes: FERMENTER / STILL / AGING
# ---------------------------------------------------------------------------
PROCESS = [
    # fermenter --------------------------------------------------------------
    D(machine="FERMENTER", result=B + "beer_light", count=2, time=1200,
      inputs=[B + "mash_grain", B + "mug", B + "mug"]),
    D(machine="FERMENTER", result=B + "beer_dark", count=2, time=1400,
      inputs=[B + "mash_grain", M + "cocoa_beans", B + "mug", B + "mug"]),
    D(machine="FERMENTER", result=B + "cider", count=2, time=1200,
      inputs=[B + "mash_fruit", B + "mug", B + "mug"]),
    D(machine="FERMENTER", result=B + "mead", count=2, time=1800,
      inputs=[B + "mash_honey", B + "mug", B + "mug"]),
    D(machine="FERMENTER", result=B + "braga", count=2, time=1000,
      inputs=[B + "mash_sugar", B + "mug", B + "mug"]),
    D(machine="FERMENTER", result=B + "potato_brew", count=2, time=1200,
      inputs=[B + "mash_potato", B + "mug", B + "mug"]),
    D(machine="FERMENTER", result=B + "mushroom_ale", count=2, time=1600,
      inputs=[B + "mash_mushroom", B + "mug", B + "mug"]),
    D(machine="FERMENTER", result=B + "pumpkin_ale", count=2, time=1400,
      inputs=[B + "mash_pumpkin", B + "mug", B + "mug"]),
    D(machine="FERMENTER", result=B + "berry_wine", count=2, time=2000,
      inputs=[B + "mash_berry", M + "glass_bottle", M + "glass_bottle"]),
    D(machine="FERMENTER", result=B + "melon_wine", count=2, time=1800,
      inputs=[B + "mash_melon", M + "glass_bottle", M + "glass_bottle"]),
    D(machine="FERMENTER", result=B + "cactus_wine", count=2, time=2000,
      inputs=[B + "mash_cactus", M + "glass_bottle", M + "glass_bottle"]),
    D(machine="FERMENTER", result=B + "chorus_wine", count=2, time=2400,
      inputs=[B + "mash_chorus", M + "glass_bottle", M + "glass_bottle"]),
    D(machine="FERMENTER", result=B + "glow_wine", count=2, time=2200,
      inputs=[B + "mash_glow", M + "glass_bottle", M + "glass_bottle"]),
    D(machine="FERMENTER", result=B + "sake", count=2, time=2600,
      inputs=[B + "mash_grain", B + "mash_grain", M + "glass_bottle", M + "glass_bottle"]),

    # still ------------------------------------------------------------------
    D(machine="STILL", result=B + "moonshine", count=1, time=800,
      inputs=[B + "braga", M + "glass_bottle"]),
    D(machine="STILL", result=B + "vodka", count=1, time=900,
      inputs=[B + "potato_brew", M + "glass_bottle"]),
    D(machine="STILL", result=B + "white_rum", count=1, time=900,
      inputs=[B + "mash_sugar", M + "glass_bottle"]),
    D(machine="STILL", result=B + "brandy", count=1, time=1000,
      inputs=[B + "cider", M + "glass_bottle"]),
    D(machine="STILL", result=B + "schnapps", count=1, time=900,
      inputs=[B + "mash_fruit", M + "glass_bottle"]),
    D(machine="STILL", result=B + "tequila", count=1, time=1000,
      inputs=[B + "mash_cactus", M + "glass_bottle"]),
    D(machine="STILL", result=B + "gin", count=1, time=1000,
      inputs=[B + "moonshine", M + "sweet_berries"]),
    D(machine="STILL", result=B + "absinthe", count=1, time=1200,
      inputs=[B + "moonshine", M + "fern"]),
    D(machine="STILL", result=B + "sambuca", count=1, time=1100,
      inputs=[B + "moonshine", M + "glow_berries", B + "shot_glass"]),
    D(machine="STILL", result=B + "dragon_absinthe", count=1, time=1600,
      inputs=[B + "absinthe", M + "dragon_breath"]),
    D(machine="STILL", result=B + "nether_whiskey", count=1, time=1400,
      inputs=[B + "whiskey", M + "blaze_powder"]),
    D(machine="STILL", result=B + "everclear", count=1, time=1200,
      inputs=[B + "moonshine", B + "moonshine"]),

    # aging barrel -----------------------------------------------------------
    D(machine="AGING", result=B + "whiskey", count=1, time=2400, inputs=[B + "moonshine"]),
    D(machine="AGING", result=B + "rum", count=1, time=2400, inputs=[B + "white_rum"]),
    D(machine="AGING", result=B + "cognac", count=1, time=3000, inputs=[B + "brandy"]),
    D(machine="AGING", result=B + "sake", count=1, time=2000, inputs=[B + "braga", M + "glass_bottle"]),
]

# ---------------------------------------------------------------------------
# Bar counter mixing
# ---------------------------------------------------------------------------
MIX = [
    D(result=B + "rum_cola", count=1, inputs=[B + "rum", B + "cola"]),
    D(result=B + "whiskey_cola", count=1, inputs=[B + "whiskey", B + "cola"]),
    D(result=B + "vodka_energy", count=1, inputs=[B + "vodka", B + "energy_classic"]),
    D(result=B + "vodka_energy", count=1, inputs=[B + "vodka", B + "energy_white"]),
    D(result=B + "screwdriver", count=1, inputs=[B + "vodka", B + "orange_juice"]),
    D(result=B + "gin_tonic", count=1, inputs=[B + "gin", B + "soda_water"]),
    D(result=B + "mojito", count=1, inputs=[B + "white_rum", B + "lemon_lime_soda"]),
    D(result=B + "margarita", count=1, inputs=[B + "tequila", B + "lemonade"]),
    D(result=B + "black_russian", count=1, inputs=[B + "vodka", B + "espresso"]),
    D(result=B + "irish_coffee", count=1, inputs=[B + "whiskey", B + "coffee"]),
    D(result=B + "sangria", count=1, inputs=[B + "berry_wine", B + "orange_juice"]),
    D(result=B + "berry_daiquiri", count=1, inputs=[B + "white_rum", B + "berry_juice"]),
    D(result=B + "absinthe_bomb", count=1, inputs=[B + "absinthe", B + "energy_white"]),
    D(result=B + "moonshine_punch", count=1, inputs=[B + "moonshine", B + "apple_juice", B + "lemonade"]),
    D(result=B + "long_island", count=1, inputs=[B + "vodka", B + "gin", B + "white_rum"]),
    D(result=B + "tequila_sunrise", count=1, inputs=[B + "tequila", B + "orange_juice"]),
    D(result=B + "dirty_swill", count=1, inputs=[B + "moonshine", B + "mushroom_ale"]),
    D(result=B + "hangover_cure", count=1, inputs=[B + "coffee", B + "orange_juice"]),
    D(result=B + "hangover_cure", count=1, inputs=[B + "milkshake", B + "espresso"]),
]

# ---------------------------------------------------------------------------
# Russian names of vanilla items, used by the documentation generator
# ---------------------------------------------------------------------------
RU_ITEMS = {
    M + "glass_pane": "Стеклянная панель",
    M + "glass_bottle": "Стеклянная бутыль",
    M + "iron_nugget": "Железный самородок",
    M + "iron_ingot": "Железный слиток",
    M + "copper_ingot": "Медный слиток",
    M + "barrel": "Бочка",
    M + "bucket": "Ведро",
    M + "water_bucket": "Ведро воды (ведро вернётся)",
    M + "milk_bucket": "Ведро молока (ведро вернётся)",
    M + "oak_planks": "Дубовые доски",
    M + "oak_slab": "Дубовая плита",
    M + "sugar": "Сахар",
    M + "wheat": "Пшеница",
    M + "potato": "Картошка",
    M + "apple": "Яблоко",
    M + "carrot": "Морковь",
    M + "sweet_berries": "Сладкие ягоды",
    M + "glow_berries": "Светящиеся ягоды",
    M + "melon_slice": "Ломтик арбуза",
    M + "cactus": "Кактус",
    M + "pumpkin": "Тыква",
    M + "chorus_fruit": "Плод хоруса",
    M + "brown_mushroom": "Коричневый гриб",
    M + "red_mushroom": "Красный гриб",
    M + "cocoa_beans": "Какао-бобы",
    M + "honey_bottle": "Бутылочка мёда",
    M + "bone_meal": "Костная мука",
    M + "glowstone_dust": "Светокаменная пыль",
    M + "dried_kelp": "Сушёная ламинария",
    M + "gunpowder": "Порох (газирация)",
    M + "fern": "Папоротник (полынь)",
    M + "dragon_breath": "Дыхание дракона",
    M + "blaze_powder": "Огненный порошок",
}

MACHINE_RU = {
    "FERMENTER": "Бродильная бочка",
    "STILL": "Самогонный аппарат",
    "AGING": "Бочка для выдержки",
}

CAT_RU = {
    "SPIRIT": "Крепкий алкоголь",
    "BEER": "Пиво и бражка",
    "WINE": "Вино",
    "COCKTAIL": "Коктейли",
    "MASH": "Закваски",
    "SODA": "Газировка",
    "ENERGY": "Энергетики",
    "COFFEE": "Кофе и чай",
    "JUICE": "Соки и лимонады",
    "MEDICINE": "Лекарства",
}

VESSEL_RU = {
    "BOTTLE": "Бутылка",
    "CUP": "Стакан",
    "MUG": "Кружка",
    "CAN": "Банка",
    "SHOT": "Рюмка",
    "NONE": "Без тары",
}
