# -*- coding: utf-8 -*-
"""Generates Java sources, resources, textures and the Russian documentation for BoozeCraft."""
import json
import os
import random
import sys

from PIL import Image

sys.path.insert(0, "/data")
from boozecraft_data import (DRINKS, TOOLS, BLOCKS, EFFECTS, CRAFTS, PROCESS, MIX,
                            RU_ITEMS, MACHINE_RU, CAT_RU, VESSEL_RU, B, M)

ROOT = "/data/boozecraft"
JAVA = os.path.join(ROOT, "src/main/java/com/s4fmer/boozecraft")
RES = os.path.join(ROOT, "src/main/resources")
ASSETS = os.path.join(RES, "assets/boozecraft")
DATA = os.path.join(RES, "data")

CAT_ORDER = ["MASH", "BEER", "WINE", "SPIRIT", "COCKTAIL", "SODA", "ENERGY", "COFFEE", "JUICE", "MEDICINE"]

EFFECT_RU = {
    "MOVEMENT_SPEED": "Скорость", "MOVEMENT_SLOWDOWN": "Замедление", "DIG_SPEED": "Спешка",
    "DIG_SLOWDOWN": "Утомление", "DAMAGE_BOOST": "Сила", "REGENERATION": "Регенерация",
    "ABSORPTION": "Поглощение", "DAMAGE_RESISTANCE": "Сопротивление урону",
    "FIRE_RESISTANCE": "Огнестойкость", "WATER_BREATHING": "Подводное дыхание",
    "NIGHT_VISION": "Ночное зрение", "JUMP": "Прыгучесть", "SLOW_FALLING": "Медленное падение",
    "LUCK": "Удача", "GLOWING": "Свечение", "DOLPHINS_GRACE": "Милость дельфина",
    "HUNGER": "Голод", "POISON": "Отравление", "CONFUSION": "Тошнота",
}


def g(d, key, default=None):
    return d.get(key, default)


def ident(item_id):
    return item_id.upper()


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def write_json(path, obj):
    write(path, json.dumps(obj, ensure_ascii=False, indent=2) + "\n")


# ---------------------------------------------------------------------------
# validation
# ---------------------------------------------------------------------------
DRINK_IDS = [d["id"] for d in DRINKS]
TOOL_IDS = [t["id"] for t in TOOLS]
BLOCK_IDS = [b["id"] for b in BLOCKS]
OWN_IDS = set(DRINK_IDS) | set(TOOL_IDS) | set(BLOCK_IDS)
problems = []

if len(DRINK_IDS) != len(set(DRINK_IDS)):
    problems.append("duplicate drink ids")


def check_ref(ref, where):
    if ref.startswith(B):
        if ref[len(B):] not in OWN_IDS:
            problems.append("unknown own item %s in %s" % (ref, where))
    elif not ref.startswith(M):
        problems.append("bad namespace %s in %s" % (ref, where))


for c in CRAFTS:
    check_ref(c["result"], "craft")
    for i in c.get("ingredients", []):
        check_ref(i, "craft " + c["result"])
    for i in c.get("key", {}).values():
        check_ref(i, "craft " + c["result"])
    if "ingredient" in c:
        check_ref(c["ingredient"], "craft " + c["result"])
for p in PROCESS:
    check_ref(p["result"], "process")
    for i in p["inputs"]:
        check_ref(i, "process " + p["result"])
mix_keys = set()
for m in MIX:
    check_ref(m["result"], "mix")
    for i in m["inputs"]:
        check_ref(i, "mix " + m["result"])
    key = "+".join(sorted(m["inputs"]))
    if key in mix_keys:
        problems.append("duplicate mix key " + key)
    mix_keys.add(key)

obtainable = set()
for c in CRAFTS:
    obtainable.add(c["result"])
for p in PROCESS:
    obtainable.add(p["result"])
for m in MIX:
    obtainable.add(m["result"])
for item_id in sorted(OWN_IDS):
    if B + item_id not in obtainable:
        problems.append("no recipe produces " + item_id)

if problems:
    print("VALIDATION PROBLEMS:")
    for p in problems:
        print("  -", p)
    sys.exit(1)
print("validation ok: %d drinks, %d tools, %d blocks, %d crafts, %d machine recipes, %d mixes"
      % (len(DRINKS), len(TOOLS), len(BLOCKS), len(CRAFTS), len(PROCESS), len(MIX)))

# ---------------------------------------------------------------------------
# Java: Drinks.java
# ---------------------------------------------------------------------------
ordered_drinks = sorted(DRINKS, key=lambda d: CAT_ORDER.index(d["cat"]))

lines = [
    "package com.s4fmer.boozecraft.drink;",
    "",
    "import java.util.Collections;",
    "import java.util.LinkedHashMap;",
    "import java.util.Map;",
    "",
    "import net.minecraft.world.effect.MobEffects;",
    "",
    "/** GENERATED by tools/boozecraft_gen.py - every drink in the mod. */",
    "public final class Drinks {",
    "",
    "\tprivate static final Map<String, DrinkDef> ALL = new LinkedHashMap<>();",
    "",
]
for d in ordered_drinks:
    abv = g(d, "abv", 0.0)
    addiction = round(abv * 10.0, 1)
    call = ["DrinkDef.builder(\"%s\")" % d["id"]]
    call.append(".cat(DrinkCategory.%s)" % d["cat"])
    call.append(".vessel(Vessel.%s)" % d["vessel"])
    call.append(".abv(%.2fD)" % abv)
    if g(d, "nutrition", 0):
        call.append(".nutrition(%d)" % d["nutrition"])
    if addiction:
        call.append(".addiction(%.1fD)" % addiction)
    if g(d, "caffeine", 0):
        call.append(".caffeine(%.1fD)" % float(d["caffeine"]))
    if g(d, "sober", 0):
        call.append(".sober(%.1fD)" % float(d["sober"]))
    if g(d, "relief", 0):
        call.append(".relief(%.1fD)" % float(d["relief"]))
    if g(d, "cure", False):
        call.append(".cure()")
    call.append(".color(0x%06X)" % d["color"])
    for fx in g(d, "fx", []):
        call.append(".fx(MobEffects.%s, %d, %d)" % (fx[0], fx[1], fx[2]))
    call.append(".build()")
    body = ""
    indent = "\t\t\t"
    current = ""
    for part in call:
        if current and len(current) + len(part) > 90:
            body += current + "\n" + indent
            current = ""
        current += part
    body += current
    lines.append("\tpublic static final DrinkDef %s = add(%s);" % (ident(d["id"]), body))
lines += [
    "",
    "\tprivate static DrinkDef add(DrinkDef def) {",
    "\t\tALL.put(def.id(), def);",
    "\t\treturn def;",
    "\t}",
    "",
    "\tpublic static Map<String, DrinkDef> all() {",
    "\t\treturn Collections.unmodifiableMap(ALL);",
    "\t}",
    "",
    "\tpublic static DrinkDef get(String id) {",
    "\t\treturn ALL.get(id);",
    "\t}",
    "",
    "\tprivate Drinks() {",
    "\t}",
    "}",
    "",
]
write(os.path.join(JAVA, "drink/Drinks.java"), "\n".join(lines))

# ---------------------------------------------------------------------------
# Java: BoozeItems.java
# ---------------------------------------------------------------------------
lines = [
    "package com.s4fmer.boozecraft.reg;",
    "",
    "import java.util.ArrayList;",
    "import java.util.LinkedHashMap;",
    "import java.util.List;",
    "import java.util.Map;",
    "",
    "import com.s4fmer.boozecraft.BoozeCraft;",
    "import com.s4fmer.boozecraft.drink.DrinkDef;",
    "import com.s4fmer.boozecraft.drink.DrinkItem;",
    "import com.s4fmer.boozecraft.drink.Drinks;",
    "import com.s4fmer.boozecraft.item.ShakerItem;",
    "import net.minecraft.world.item.BlockItem;",
    "import net.minecraft.world.item.Item;",
    "import net.minecraft.world.level.block.Block;",
    "import net.neoforged.neoforge.registries.DeferredBlock;",
    "import net.neoforged.neoforge.registries.DeferredItem;",
    "import net.neoforged.neoforge.registries.DeferredRegister;",
    "",
    "/** GENERATED by tools/boozecraft_gen.py - item registry. */",
    "public final class BoozeItems {",
    "",
    "\tpublic static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(BoozeCraft.MODID);",
    "",
    "\t/** Creative tab order, filled while the fields below are initialised. */",
    "\tpublic static final List<DeferredItem<? extends Item>> CREATIVE_ORDER = new ArrayList<>();",
    "\tprivate static final Map<String, DeferredItem<Item>> DRINKS = new LinkedHashMap<>();",
    "",
    "\t// ---- glassware and tools ----",
]
for t in TOOLS:
    if t["cls"] == "ShakerItem":
        lines.append("\tpublic static final DeferredItem<Item> %s = shaker(\"%s\");" % (ident(t["id"]), t["id"]))
    else:
        lines.append("\tpublic static final DeferredItem<Item> %s = tool(\"%s\", %d);"
                     % (ident(t["id"]), t["id"], t["stack"]))
lines.append("")
last_cat = None
for d in ordered_drinks:
    if d["cat"] != last_cat:
        lines.append("")
        lines.append("\t// ---- %s ----" % d["cat"].lower())
        last_cat = d["cat"]
    lines.append("\tpublic static final DeferredItem<Item> %s = drink(Drinks.%s, %d);"
                 % (ident(d["id"]), ident(d["id"]), g(d, "stack", 16)))
lines.append("")
lines.append("\t// ---- blocks ----")
for b in BLOCKS:
    lines.append("\tpublic static final DeferredItem<Item> %s = blockItem(\"%s\", BoozeBlocks.%s);"
                 % (ident(b["id"]), b["id"], ident(b["id"])))
lines += [
    "",
    "\tprivate static DeferredItem<Item> tool(String name, int stackSize) {",
    "\t\tDeferredItem<Item> item = ITEMS.register(name, () -> new Item(new Item.Properties().stacksTo(stackSize)));",
    "\t\tCREATIVE_ORDER.add(item);",
    "\t\treturn item;",
    "\t}",
    "",
    "\tprivate static DeferredItem<Item> shaker(String name) {",
    "\t\tDeferredItem<Item> item = ITEMS.register(name, () -> new ShakerItem(new Item.Properties().stacksTo(1)));",
    "\t\tCREATIVE_ORDER.add(item);",
    "\t\treturn item;",
    "\t}",
    "",
    "\tprivate static DeferredItem<Item> drink(DrinkDef def, int stackSize) {",
    "\t\tDeferredItem<Item> item = ITEMS.register(def.id(),",
    "\t\t\t\t() -> new DrinkItem(def, new Item.Properties().stacksTo(stackSize)));",
    "\t\tCREATIVE_ORDER.add(item);",
    "\t\tDRINKS.put(def.id(), item);",
    "\t\treturn item;",
    "\t}",
    "",
    "\tprivate static DeferredItem<Item> blockItem(String name, DeferredBlock<Block> block) {",
    "\t\tDeferredItem<Item> item = ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));",
    "\t\tCREATIVE_ORDER.add(item);",
    "\t\treturn item;",
    "\t}",
    "",
    "\t/** Registered drink item by drink id, or null. */",
    "\tpublic static DeferredItem<Item> drink(String id) {",
    "\t\treturn DRINKS.get(id);",
    "\t}",
    "",
    "\tpublic static Map<String, DeferredItem<Item>> drinks() {",
    "\t\treturn DRINKS;",
    "\t}",
    "",
    "\tprivate BoozeItems() {",
    "\t}",
    "}",
    "",
]
write(os.path.join(JAVA, "reg/BoozeItems.java"), "\n".join(lines))

# ---------------------------------------------------------------------------
# Java: ProcessRecipes.java
# ---------------------------------------------------------------------------
lines = [
    "package com.s4fmer.boozecraft.recipe;",
    "",
    "import java.util.ArrayList;",
    "import java.util.HashMap;",
    "import java.util.List;",
    "import java.util.Map;",
    "",
    "import com.s4fmer.boozecraft.block.ProcessorType;",
    "import net.minecraft.core.NonNullList;",
    "import net.minecraft.core.registries.BuiltInRegistries;",
    "import net.minecraft.resources.ResourceLocation;",
    "import net.minecraft.world.item.Item;",
    "import net.minecraft.world.item.ItemStack;",
    "",
    "/** GENERATED by tools/boozecraft_gen.py - fermenter / still / aging barrel recipes. */",
    "public final class ProcessRecipes {",
    "",
    "\tpublic static final class Entry {",
    "\t\tpublic final ProcessorType type;",
    "\t\tpublic final String[] inputs;",
    "\t\tpublic final String result;",
    "\t\tpublic final int count;",
    "\t\tpublic final int time;",
    "",
    "\t\tEntry(ProcessorType type, String result, int count, int time, String[] inputs) {",
    "\t\t\tthis.type = type;",
    "\t\t\tthis.result = result;",
    "\t\t\tthis.count = count;",
    "\t\t\tthis.time = time;",
    "\t\t\tthis.inputs = inputs;",
    "\t\t}",
    "\t}",
    "",
    "\tprivate static final List<Entry> ALL = new ArrayList<>();",
    "",
    "\tstatic {",
]
for p in PROCESS:
    args = ", ".join("\"%s\"" % i for i in p["inputs"])
    lines.append("\t\tadd(ProcessorType.%s, \"%s\", %d, %d, %s);"
                 % (p["machine"], p["result"], p["count"], p["time"], args))
lines += [
    "\t\tALL.sort((a, b) -> Integer.compare(b.inputs.length, a.inputs.length));",
    "\t}",
    "",
    "\tprivate static void add(ProcessorType type, String result, int count, int time, String... inputs) {",
    "\t\tALL.add(new Entry(type, result, count, time, inputs));",
    "\t}",
    "",
    "\tpublic static List<Entry> all() {",
    "\t\treturn ALL;",
    "\t}",
    "",
    "\tpublic static Item item(String id) {",
    "\t\treturn BuiltInRegistries.ITEM.getOptional(ResourceLocation.parse(id)).orElse(null);",
    "\t}",
    "",
    "\t/** Finds a recipe whose ingredients are all present and where nothing foreign is inside. */",
    "\tpublic static Entry find(ProcessorType type, NonNullList<ItemStack> items, int inputSlots) {",
    "\t\tMap<Item, Integer> have = new HashMap<>();",
    "\t\tint total = 0;",
    "\t\tfor (int i = 0; i < inputSlots; i++) {",
    "\t\t\tItemStack stack = items.get(i);",
    "\t\t\tif (!stack.isEmpty()) {",
    "\t\t\t\thave.merge(stack.getItem(), stack.getCount(), Integer::sum);",
    "\t\t\t\ttotal += stack.getCount();",
    "\t\t\t}",
    "\t\t}",
    "\t\tif (total == 0) {",
    "\t\t\treturn null;",
    "\t\t}",
    "\t\touter:",
    "\t\tfor (Entry entry : ALL) {",
    "\t\t\tif (entry.type != type) {",
    "\t\t\t\tcontinue;",
    "\t\t\t}",
    "\t\t\tMap<Item, Integer> need = new HashMap<>();",
    "\t\t\tfor (String id : entry.inputs) {",
    "\t\t\t\tItem item = item(id);",
    "\t\t\t\tif (item == null) {",
    "\t\t\t\t\tcontinue outer;",
    "\t\t\t\t}",
    "\t\t\t\tneed.merge(item, 1, Integer::sum);",
    "\t\t\t}",
    "\t\t\tfor (Map.Entry<Item, Integer> requirement : need.entrySet()) {",
    "\t\t\t\tInteger got = have.get(requirement.getKey());",
    "\t\t\t\tif (got == null || got.intValue() < requirement.getValue().intValue()) {",
    "\t\t\t\t\tcontinue outer;",
    "\t\t\t\t}",
    "\t\t\t}",
    "\t\t\tfor (Item present : have.keySet()) {",
    "\t\t\t\tif (!need.containsKey(present)) {",
    "\t\t\t\t\tcontinue outer;",
    "\t\t\t\t}",
    "\t\t\t}",
    "\t\t\treturn entry;",
    "\t\t}",
    "\t\treturn null;",
    "\t}",
    "",
    "\tpublic static void consume(Entry entry, NonNullList<ItemStack> items, int inputSlots) {",
    "\t\tfor (String id : entry.inputs) {",
    "\t\t\tItem item = item(id);",
    "\t\t\tif (item == null) {",
    "\t\t\t\tcontinue;",
    "\t\t\t}",
    "\t\t\tfor (int i = 0; i < inputSlots; i++) {",
    "\t\t\t\tItemStack stack = items.get(i);",
    "\t\t\t\tif (!stack.isEmpty() && stack.getItem() == item) {",
    "\t\t\t\t\tstack.shrink(1);",
    "\t\t\t\t\tbreak;",
    "\t\t\t\t}",
    "\t\t\t}",
    "\t\t}",
    "\t}",
    "",
    "\tprivate ProcessRecipes() {",
    "\t}",
    "}",
    "",
]
write(os.path.join(JAVA, "recipe/ProcessRecipes.java"), "\n".join(lines))

# ---------------------------------------------------------------------------
# Java: MixRecipes.java
# ---------------------------------------------------------------------------
lines = [
    "package com.s4fmer.boozecraft.recipe;",
    "",
    "import java.util.ArrayList;",
    "import java.util.Arrays;",
    "import java.util.Collection;",
    "import java.util.LinkedHashMap;",
    "import java.util.List;",
    "import java.util.Map;",
    "",
    "import net.minecraft.core.registries.BuiltInRegistries;",
    "import net.minecraft.resources.ResourceLocation;",
    "import net.minecraft.world.item.Item;",
    "",
    "/** GENERATED by tools/boozecraft_gen.py - bar counter mixing recipes. */",
    "public final class MixRecipes {",
    "",
    "\tpublic static final class Entry {",
    "\t\tpublic final String result;",
    "\t\tpublic final int count;",
    "\t\tpublic final String[] inputs;",
    "",
    "\t\tEntry(String result, int count, String[] inputs) {",
    "\t\t\tthis.result = result;",
    "\t\t\tthis.count = count;",
    "\t\t\tthis.inputs = inputs;",
    "\t\t}",
    "\t}",
    "",
    "\tprivate static final Map<String, Entry> ALL = new LinkedHashMap<>();",
    "",
    "\tstatic {",
]
for m in MIX:
    args = ", ".join("\"%s\"" % i for i in m["inputs"])
    lines.append("\t\tadd(\"%s\", %d, %s);" % (m["result"], m["count"], args))
lines += [
    "\t}",
    "",
    "\tprivate static void add(String result, int count, String... inputs) {",
    "\t\tALL.put(key(inputs), new Entry(result, count, inputs));",
    "\t}",
    "",
    "\tprivate static String key(String[] ids) {",
    "\t\tString[] copy = ids.clone();",
    "\t\tArrays.sort(copy);",
    "\t\treturn String.join(\"+\", copy);",
    "\t}",
    "",
    "\tpublic static Entry find(List<String> ids) {",
    "\t\treturn ALL.get(key(ids.toArray(new String[0])));",
    "\t}",
    "",
    "\tpublic static Collection<Entry> all() {",
    "\t\treturn new ArrayList<>(ALL.values());",
    "\t}",
    "",
    "\tpublic static Item item(String id) {",
    "\t\treturn BuiltInRegistries.ITEM.getOptional(ResourceLocation.parse(id)).orElse(null);",
    "\t}",
    "",
    "\tprivate MixRecipes() {",
    "\t}",
    "}",
    "",
]
write(os.path.join(JAVA, "recipe/MixRecipes.java"), "\n".join(lines))
print("java written")

# ---------------------------------------------------------------------------
# resources: models, blockstates, recipes, loot tables, tags
# ---------------------------------------------------------------------------
for item_id in DRINK_IDS + TOOL_IDS:
    write_json(os.path.join(ASSETS, "models/item/%s.json" % item_id),
               {"parent": "minecraft:item/generated", "textures": {"layer0": "boozecraft:item/" + item_id}})

for b in BLOCKS:
    bid = b["id"]
    write_json(os.path.join(ASSETS, "blockstates/%s.json" % bid),
               {"variants": {"": {"model": "boozecraft:block/" + bid}}})
    write_json(os.path.join(ASSETS, "models/block/%s.json" % bid), {
        "parent": "minecraft:block/cube_bottom_top",
        "textures": {
            "top": "boozecraft:block/%s_top" % bid,
            "side": "boozecraft:block/%s_side" % bid,
            "bottom": "boozecraft:block/%s_side" % bid,
        },
    })
    write_json(os.path.join(ASSETS, "models/item/%s.json" % bid), {"parent": "boozecraft:block/" + bid})
    write_json(os.path.join(DATA, "boozecraft/loot_table/blocks/%s.json" % bid), {
        "type": "minecraft:block",
        "pools": [{
            "rolls": 1,
            "bonus_rolls": 0,
            "entries": [{"type": "minecraft:item", "name": "boozecraft:" + bid}],
            "conditions": [{"condition": "minecraft:survives_explosion"}],
        }],
    })

for tool_name in ("axe", "pickaxe"):
    values = ["boozecraft:" + b["id"] for b in BLOCKS if b["tool"] == tool_name]
    if values:
        write_json(os.path.join(DATA, "minecraft/tags/block/mineable/%s.json" % tool_name),
                   {"replace": False, "values": values})


def recipe_name(c):
    if "name" in c:
        return c["name"]
    return c["result"].split(":")[1]


for c in CRAFTS:
    name = recipe_name(c)
    if c["kind"] == "shaped":
        obj = {
            "type": "minecraft:crafting_shaped",
            "category": "misc",
            "pattern": c["pattern"],
            "key": {k: {"item": v} for k, v in c["key"].items()},
            "result": {"id": c["result"], "count": c["count"]},
        }
    elif c["kind"] == "shapeless":
        obj = {
            "type": "minecraft:crafting_shapeless",
            "category": "misc",
            "ingredients": [{"item": i} for i in c["ingredients"]],
            "result": {"id": c["result"], "count": c["count"]},
        }
    else:
        obj = {
            "type": "minecraft:smelting",
            "category": "food",
            "ingredient": {"item": c["ingredient"]},
            "result": {"id": c["result"], "count": c["count"]},
            "experience": c["exp"],
            "cookingtime": c["time"],
        }
    write_json(os.path.join(DATA, "boozecraft/recipe/%s.json" % name), obj)
print("resources written")

# ---------------------------------------------------------------------------
# lang
# ---------------------------------------------------------------------------
MSG = {
    "itemGroup.boozecraft": ("BoozeCraft", "BoozeCraft"),
    "tooltip.boozecraft.abv": ("Alcohol: %s%%", "Алкоголь: %s%%"),
    "tooltip.boozecraft.caffeine": ("Caffeine: %s", "Кофеин: %s"),
    "tooltip.boozecraft.cures": ("Cures a hangover", "Лечит похмелье"),
    "tooltip.boozecraft.relief": ("Eases addiction", "Ослабляет зависимость"),
    "tooltip.boozecraft.starter": ("Has starter effects while sober", "Даёт эффекты, пока вы трезвы"),
    "tooltip.boozecraft.mixable": ("Can be mixed on a bar counter", "Можно смешивать на барной стойке"),
    "tooltip.boozecraft.shaker": ("Mixes drinks placed on a bar counter",
                                  "Смешивает напитки, стоящие на барной стойке"),
    "msg.boozecraft.stage_tipsy": ("You feel a little tipsy...", "Вы слегка навеселе..."),
    "msg.boozecraft.stage_drunk": ("You are drunk.", "Вы пьяны."),
    "msg.boozecraft.stage_heavy": ("The world is spinning...", "Мир поплыл перед глазами..."),
    "msg.boozecraft.stage_sober": ("You are sober again.", "Вы протрезвели."),
    "msg.boozecraft.too_drunk_for_effects": ("You are too drunk to feel anything nice.",
                                             "Вы слишком пьяны, чтобы почувствовать вкус."),
    "msg.boozecraft.addicted": ("You cannot stop thinking about the next drink...",
                                "Вы больше не можете не думать о следующей рюмке..."),
    "msg.boozecraft.withdrawal": ("Your hands are shaking. You need a drink.",
                                  "Руки трясутся. Нужно выпить."),
    "msg.boozecraft.hangover_start": ("Your head is pounding.", "Голова раскалывается."),
    "msg.boozecraft.vomit": ("You throw up.", "Вас вырвало."),
    "msg.boozecraft.passed_out": ("You pass out...", "Вас вырубило..."),
    "msg.boozecraft.woke_up": ("You wake up. What happened?", "Вы просыпаетесь. Что произошло?"),
    "msg.boozecraft.milk": ("The milk clears your head.", "Молоко проясняет голову."),
    "msg.boozecraft.machine_full": ("No free slot left.", "Нет свободных слотов."),
    "msg.boozecraft.progress": ("%1$s: %2$s%% ready", "%1$s: готово на %2$s%%"),
    "msg.boozecraft.idle": ("%1$s: nothing to do", "%1$s: нечего делать"),
    "msg.boozecraft.no_heat": ("The still needs fire, lava or a lit campfire below it.",
                               "Самогонному аппарату нужен огонь, лава или костёр снизу."),
    "msg.boozecraft.counter_full": ("The counter is full.", "На стойке нет места."),
    "msg.boozecraft.counter_empty": ("There is nothing on the counter.", "На стойке ничего нет."),
    "msg.boozecraft.need_more": ("Place at least two drinks on the counter.",
                                 "Поставьте на стойку хотя бы два напитка."),
    "msg.boozecraft.no_recipe": ("These drinks do not mix.", "Эти напитки не смешиваются."),
    "msg.boozecraft.mixed": ("Mixed: %s", "Смешано: %s"),
    "msg.boozecraft.machine.fermenter": ("Fermenter", "Бродильная бочка"),
    "msg.boozecraft.machine.still": ("Still", "Самогонный аппарат"),
    "msg.boozecraft.machine.aging_barrel": ("Aging barrel", "Бочка для выдержки"),
}

en = {}
ru = {}
for d in DRINKS:
    en["item.boozecraft." + d["id"]] = d["en"]
    ru["item.boozecraft." + d["id"]] = d["ru"]
for t in TOOLS:
    en["item.boozecraft." + t["id"]] = t["en"]
    ru["item.boozecraft." + t["id"]] = t["ru"]
for b in BLOCKS:
    en["block.boozecraft." + b["id"]] = b["en"]
    ru["block.boozecraft." + b["id"]] = b["ru"]
for e in EFFECTS:
    en["effect.boozecraft." + e["id"]] = e["en"]
    ru["effect.boozecraft." + e["id"]] = e["ru"]
for key, (english, russian) in MSG.items():
    en[key] = english
    ru[key] = russian
write_json(os.path.join(ASSETS, "lang/en_us.json"), en)
write_json(os.path.join(ASSETS, "lang/ru_ru.json"), ru)
print("lang written: %d keys" % len(en))

# ---------------------------------------------------------------------------
# textures (16x16 items/blocks, 18x18 effect icons)
# ---------------------------------------------------------------------------
random.seed(20260822)

GLASS = (198, 224, 236, 130)
GLASS_D = (150, 180, 196, 170)
OUTLINE = (26, 20, 16, 255)
METAL = (176, 180, 188, 255)
METAL_D = (112, 118, 126, 255)
SHINE = (255, 255, 255, 95)


def rgb(value, alpha=255):
    return ((value >> 16) & 255, (value >> 8) & 255, value & 255, alpha)


def shade(value, factor):
    r = max(0, min(255, int(((value >> 16) & 255) * factor)))
    gg = max(0, min(255, int(((value >> 8) & 255) * factor)))
    b = max(0, min(255, int((value & 255) * factor)))
    return (r << 16) | (gg << 8) | b


def new_img(size=16):
    return Image.new("RGBA", (size, size), (0, 0, 0, 0))


def rect(px, x0, y0, x1, y1, col):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            px[x, y] = col


def hline(px, x0, x1, y, col):
    for x in range(x0, x1 + 1):
        px[x, y] = col


def vline(px, x, y0, y1, col):
    for y in range(y0, y1 + 1):
        px[x, y] = col


def box(px, x0, y0, x1, y1, col):
    hline(px, x0, x1, y0, col)
    hline(px, x0, x1, y1, col)
    vline(px, x0, y0, y1, col)
    vline(px, x1, y0, y1, col)


def speckle(px, x0, y0, x1, y1, col, chance=0.25):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            if random.random() < chance:
                px[x, y] = col


def tex_bottle(color, accent, filled=True):
    im = new_img()
    px = im.load()
    liquid = rgb(color)
    dark = rgb(shade(color, 0.65))
    rect(px, 6, 0, 9, 1, rgb(accent))
    rect(px, 6, 2, 9, 4, GLASS)
    vline(px, 6, 2, 4, OUTLINE)
    vline(px, 9, 2, 4, OUTLINE)
    rect(px, 4, 5, 11, 15, GLASS)
    if filled:
        rect(px, 5, 8, 10, 14, liquid)
        hline(px, 5, 10, 14, dark)
        hline(px, 5, 10, 8, rgb(shade(color, 1.2)))
    box(px, 4, 5, 11, 15, OUTLINE)
    vline(px, 5, 6, 7, SHINE)
    return im


def tex_can(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 4, 2, 11, 14, rgb(color) if filled else METAL)
    rect(px, 4, 1, 11, 2, METAL)
    rect(px, 4, 14, 11, 15, METAL_D)
    rect(px, 4, 7, 11, 9, rgb(accent))
    box(px, 4, 1, 11, 15, OUTLINE)
    vline(px, 5, 3, 13, SHINE)
    px[7, 1] = METAL_D
    px[8, 1] = METAL_D
    return im


def tex_cup(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 4, 4, 11, 14, GLASS)
    if filled:
        rect(px, 5, 7, 10, 13, rgb(color))
        hline(px, 5, 10, 7, rgb(shade(color, 1.2)))
        hline(px, 5, 10, 13, rgb(shade(color, 0.65)))
    box(px, 4, 4, 11, 14, OUTLINE)
    hline(px, 5, 10, 15, GLASS_D)
    vline(px, 5, 5, 6, SHINE)
    return im


def tex_mug(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 3, 3, 10, 14, GLASS)
    if filled:
        rect(px, 4, 6, 9, 13, rgb(color))
        rect(px, 4, 4, 9, 5, (255, 250, 240, 220))
        hline(px, 4, 9, 13, rgb(shade(color, 0.65)))
    box(px, 3, 3, 10, 14, OUTLINE)
    box(px, 11, 6, 13, 11, OUTLINE)
    rect(px, 12, 7, 12, 10, GLASS_D)
    vline(px, 4, 4, 5, SHINE)
    return im


def tex_shot(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 5, 7, 10, 14, GLASS)
    if filled:
        rect(px, 6, 9, 9, 13, rgb(color))
        hline(px, 6, 9, 9, rgb(shade(color, 1.2)))
    box(px, 5, 7, 10, 14, OUTLINE)
    hline(px, 6, 9, 15, GLASS_D)
    px[6, 8] = SHINE
    return im


def tex_jar(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 4, 2, 11, 3, rgb(accent))
    rect(px, 3, 4, 12, 14, GLASS)
    if filled:
        rect(px, 4, 6, 11, 13, rgb(color))
        speckle(px, 4, 6, 11, 13, rgb(shade(color, 0.8)), 0.18)
        hline(px, 4, 11, 13, rgb(shade(color, 0.6)))
    box(px, 3, 4, 12, 14, OUTLINE)
    box(px, 4, 2, 11, 3, OUTLINE)
    vline(px, 4, 5, 6, SHINE)
    return im


def tex_pill(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 4, 6, 11, 10, (248, 248, 248, 255))
    rect(px, 4, 6, 7, 10, rgb(accent))
    box(px, 4, 6, 11, 10, OUTLINE)
    px[5, 7] = (255, 255, 255, 160)
    return im


def tex_shaker(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 5, 1, 10, 3, METAL_D)
    rect(px, 4, 4, 11, 14, METAL)
    rect(px, 4, 8, 11, 9, METAL_D)
    box(px, 4, 4, 11, 14, OUTLINE)
    box(px, 5, 1, 10, 3, OUTLINE)
    vline(px, 5, 5, 13, SHINE)
    return im


def tex_beans(color, accent, filled=True):
    im = new_img()
    px = im.load()
    for (cx, cy) in ((5, 5), (10, 7), (7, 11)):
        rect(px, cx - 1, cy - 2, cx + 1, cy + 2, rgb(color))
        box(px, cx - 1, cy - 2, cx + 1, cy + 2, OUTLINE)
        vline(px, cx, cy - 1, cy + 1, rgb(shade(color, 0.55)))
    return im


def tex_powder(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 3, 11, 12, 14, rgb(color))
    rect(px, 5, 9, 10, 10, rgb(color))
    rect(px, 7, 8, 8, 8, rgb(color))
    speckle(px, 3, 8, 12, 14, rgb(shade(color, 0.75)), 0.2)
    hline(px, 3, 12, 15, rgb(shade(color, 0.6)))
    return im


def tex_syrup(color, accent, filled=True):
    im = new_img()
    px = im.load()
    rect(px, 7, 1, 8, 3, rgb(accent))
    rect(px, 5, 4, 10, 14, GLASS)
    rect(px, 6, 6, 9, 13, rgb(color))
    box(px, 5, 4, 10, 14, OUTLINE)
    px[6, 5] = SHINE
    return im


TEMPLATES = {
    "bottle": tex_bottle,
    "can": tex_can,
    "cup": tex_cup,
    "mug": tex_mug,
    "shot": tex_shot,
    "jar": tex_jar,
    "pill": tex_pill,
    "shaker": tex_shaker,
    "beans": tex_beans,
    "powder": tex_powder,
}

TOOL_TEX = {
    "cup_empty": (tex_cup, 0xBFD8E6, False),
    "mug_empty": (tex_mug, 0xBFD8E6, False),
    "shot_empty": (tex_shot, 0xBFD8E6, False),
    "can_empty": (tex_can, 0xB0B4BC, False),
    "shaker": (tex_shaker, 0xB0B4BC, True),
    "beans": (tex_beans, 0x5A3A22, True),
    "powder": (tex_powder, 0xE8DCC0, True),
    "syrup_soda": (tex_syrup, 0x3A1E14, True),
    "syrup_energy": (tex_syrup, 0x8CC63F, True),
}

ITEM_TEX_DIR = os.path.join(ASSETS, "textures/item")
BLOCK_TEX_DIR = os.path.join(ASSETS, "textures/block")
EFFECT_TEX_DIR = os.path.join(ASSETS, "textures/mob_effect")
for folder in (ITEM_TEX_DIR, BLOCK_TEX_DIR, EFFECT_TEX_DIR):
    os.makedirs(folder, exist_ok=True)

texture_count = 0
for d in DRINKS:
    template = TEMPLATES.get(g(d, "tex", "bottle"), tex_bottle)
    color = g(d, "color", 0xC0A060)
    accent = g(d, "accent", shade(color, 0.55))
    template(color, accent, True).save(os.path.join(ITEM_TEX_DIR, d["id"] + ".png"))
    texture_count += 1

for t in TOOLS:
    template, color, filled = TOOL_TEX.get(g(t, "tex", "powder"), (tex_powder, 0xC0C0C0, True))
    accent = shade(color, 0.6)
    template(color, accent, filled).save(os.path.join(ITEM_TEX_DIR, t["id"] + ".png"))
    texture_count += 1

for b in BLOCKS:
    top = g(b, "top", 0x8A5A28)
    side = g(b, "side", 0x6A4520)
    band = g(b, "band", 0xC8A050)

    im = new_img()
    px = im.load()
    rect(px, 0, 0, 15, 15, rgb(top))
    speckle(px, 0, 0, 15, 15, rgb(shade(top, 0.88)), 0.22)
    box(px, 0, 0, 15, 15, rgb(shade(top, 0.55)))
    box(px, 3, 3, 12, 12, rgb(band))
    rect(px, 6, 6, 9, 9, rgb(shade(top, 0.7)))
    im.save(os.path.join(BLOCK_TEX_DIR, b["id"] + "_top.png"))
    texture_count += 1

    im = new_img()
    px = im.load()
    rect(px, 0, 0, 15, 15, rgb(side))
    speckle(px, 0, 0, 15, 15, rgb(shade(side, 0.85)), 0.25)
    rect(px, 0, 3, 15, 4, rgb(band))
    rect(px, 0, 11, 15, 12, rgb(band))
    hline(px, 0, 15, 0, rgb(shade(side, 1.2)))
    hline(px, 0, 15, 15, rgb(shade(side, 0.6)))
    im.save(os.path.join(BLOCK_TEX_DIR, b["id"] + "_side.png"))
    texture_count += 1

for e in EFFECTS:
    color = g(e, "color", 0x808080)
    im = Image.new("RGBA", (18, 18), (0, 0, 0, 0))
    px = im.load()
    rect(px, 2, 2, 15, 15, rgb(color))
    box(px, 2, 2, 15, 15, rgb(shade(color, 0.5)))
    box(px, 1, 1, 16, 16, (0, 0, 0, 90))
    for i in range(4, 13):
        px[i, i] = rgb(shade(color, 1.45))
        px[i, 17 - i] = rgb(shade(color, 0.65))
    im.save(os.path.join(EFFECT_TEX_DIR, e["id"] + ".png"))
    texture_count += 1

print("textures written: %d" % texture_count)

# ---------------------------------------------------------------------------
# documentation (Russian) + README
# ---------------------------------------------------------------------------
RU_ALL = {}
for d in DRINKS:
    RU_ALL[B + d["id"]] = d["ru"]
for t in TOOLS:
    RU_ALL[B + t["id"]] = t["ru"]
for b in BLOCKS:
    RU_ALL[B + b["id"]] = b["ru"]
RU_ALL.update(RU_ITEMS)


def ru_name(ref):
    if ref in RU_ALL:
        return RU_ALL[ref]
    return ref.split(":")[-1].replace("_", " ")


def ru_list(refs):
    counts = []
    for ref in refs:
        if counts and counts[-1][0] == ref:
            counts[-1][1] += 1
        else:
            counts.append([ref, 1])
    parts = []
    for ref, amount in counts:
        parts.append(ru_name(ref) + (" ×%d" % amount if amount > 1 else ""))
    return ", ".join(parts)


def fx_text(d):
    parts = []
    for entry in g(d, "fx", []) or []:
        name, seconds, amp = entry[0], entry[1], entry[2]
        text = "%s %dс" % (EFFECT_RU.get(name, name), seconds)
        if amp:
            text += " (ур. %d)" % (amp + 1)
        parts.append(text)
    return ", ".join(parts) if parts else "—"


def extra_text(d):
    bits = []
    if g(d, "caffeine"):
        bits.append("кофеин +%g" % d["caffeine"])
    if g(d, "nutrition"):
        bits.append("сытость +%g" % d["nutrition"])
    if g(d, "sober"):
        bits.append("−%g опьянения" % d["sober"])
    if g(d, "relief"):
        bits.append("−%g зависимости" % d["relief"])
    if g(d, "cure"):
        bits.append("снимает похмелье и абстиненцию")
    return ", ".join(bits) if bits else "—"


def abv_text(d):
    abv = g(d, "abv", 0.0) or 0.0
    if abv <= 0:
        return "0 %"
    return "%.0f %%" % (abv * 100.0)


def schema_cell(c):
    rows = []
    for row in c["pattern"]:
        rows.append("`" + row.replace(" ", ".") + "`")
    return "<br>".join(rows)


def legend_cell(c):
    parts = []
    for symbol, ref in c["key"].items():
        parts.append("`%s` — %s" % (symbol, ru_name(ref)))
    return "<br>".join(parts)


L = []
A = L.append

A("# BoozeCraft — полная документация")
A("")
A("Мод для **Minecraft 1.21.1**, **NeoForge 21.1.248**. Алкоголь, газировка, энергетики, кофе,")
A("стеклянная посуда, три аппарата для производства и барная стойка со смешиванием.")
A("")
A("* Мод-ID: `boozecraft`, версия `1.0.0`, лицензия MIT.")
A("* Вся игровая логика — **на сервере**. Мультиплеер поддерживается полностью.")
A("* Нет миксинов, access-transformer'ов, своих пакетов и своих GUI → мод спокойно работает")
A("  на гибридных серверах **Youer / Mohist / Arclight** (NeoForge + Bukkit/Paper API).")
A("* Клиент нужен такой же, как и сервер (это обычный мод, не плагин): игроки ставят jar в `mods`.")
A("")
A("---")
A("")
A("## 1. Установка")
A("")
A("1. Установите NeoForge **21.1.248** для Minecraft 1.21.1 (на сервер и на клиент).")
A("2. Положите `boozecraft-1.0.0.jar` в папку `mods` на сервере и у каждого игрока.")
A("3. Запустите сервер один раз — появятся файлы конфигурации:")
A("   * `config/boozecraft-server.toml` — вся механика опьянения (правится только на сервере);")
A("   * `config/boozecraft-client.toml` — покачивание камеры (у каждого игрока своё).")
A("4. Данные игроков (опьянение, зависимость, кофеин) хранятся в файле мира")
A("   `<мир>/boozecraft_players.json`, поэтому переносятся вместе с миром.")
A("")
A("### Youer / Mohist / Arclight")
A("")
A("Мод складывается в `mods`, плагины остаются в `plugins`. Дополнительно ничего настраивать не нужно.")
A("Мод вызывает команды сервера (например `lay` из GSit) через обычную консоль команд Minecraft,")
A("а гибридное ядро пробрасывает их в Bukkit-плагины — так работает связка с GSit.")
A("")
A("---")
A("")
A("## 2. Как работает опьянение")
A("")
A("У каждого игрока есть скрытая шкала алкоголя (0…150). Один напиток даёт `крепость × 55` очков,")
A("шкала падает примерно на `0.18` в секунду (≈11 очков в минуту).")
A("")
A("| Стадия | Порог | Что происходит |")
A("|---|---|---|")
A("| Навеселе (`tipsy`) | от 1 | косметический эффект, лёгкое покачивание камеры |")
A("| Опьянение (`drunk`) | от 20 | замедление, тошнота, игрока шатает при ходьбе |")
A("| Сильное опьянение (`heavy_drunk`) | от 55 | сильное шатание, тошнота, слепота вспышками, рвота, шанс вырубиться |")
A("")
A("Средняя пьянка (2–4 крепких напитка) — это как раз **2–3 минуты** сильного опьянения")
A("плюс несколько минут «отходняка», как и просили. Значения порогов и скорость")
A("протрезвления настраиваются в конфиге.")
A("")
A("### Эффекты «в начале»")
A("")
A("Каждый напиток имеет свои приятные эффекты (скорость, сила, регенерация…), но они выдаются")
A("**только пока игрок относительно трезв** (шкала ниже порога опьянения). Если выпить пьяным,")
A("в чат придёт сообщение, что эффекты уже не действуют — остаётся только опьянение.")
A("Отключается опцией `starterEffectsOnlyWhenSober`.")
A("")
A("### Вырубание (GSit `lay`)")
A("")
A("При сильном опьянении есть шанс (по умолчанию 1.2 % в секунду) что игрока просто уложит:")
A("")
A("* мод выполняет команду из `passOut.commands` (по умолчанию `lay` — это GSit);")
A("* игрок получает эффект `Вырубило`, сильное замедление, слабость и (опционально) слепоту;")
A("* пока игрок лежит, мод **держит его на месте**: сбрасывает скорость, возвращает на точку")
A("  падения и раз в секунду повторяет команду `lay`, если игрок как-то встал")
A("  (`passOut.reapplyCommand`). Встать раньше времени не получится;")
A("* длительность — от 20 до 45 секунд (`passOut.secondsMin/Max`);")
A("* после пробуждения выполняются команды из `passOut.endCommands` (например `getup`).")
A("")
A("Если GSit нет (или это ванильный NeoForge-сервер) — мод сам кладёт игрока в позу лежа")
A("(`passOut.forcePoseFallback`), так что фича работает и без плагинов.")
A("")
A("Права GSit: игрокам нужен `gsit.lay` (или выдайте `gsit.*`). Команда выполняется от имени")
A("игрока с правами оператора, поэтому обычно ничего настраивать не нужно.")
A("")
A("### Похмелье")
A("")
A("Если игрок доходил до сильного опьянения, после протрезвления начинается похмелье на 3 минуты:")
A("слабость, усталость, редкая тошнота. Лечится молоком, `Аспирином` или коктейлем `Антипохмелин`.")
A("")
A("### Зависимость и абстиненция")
A("")
A("Каждый крепкий напиток добавляет очки зависимости (0…100), а если пить часто (реже чем раз")
A("в 2 минуты — множитель ×1.5). При 40 очках игрок становится зависимым: если не пить")
A("10 минут, начинается абстиненция — слабость, усталость, тошнота и сообщения в экране.")
A("Зависимость медленно спадает (0.8 очка в минуту трезвости), быстрее — от `Аспирина`.")
A("")
A("### Кофеин")
A("")
A("Кофе и энергетики дают отдельную шкалу кофеина (0…200): ускорение добычи, лёгкое")
A("протрезвление (`caffeine.soberFactor`), а после 80 очков — тремор `Кофеиновый тремор`")
A("с тошнотой. Кофеин отлично комбинируется с алкоголем в коктейлях.")
A("")
A("### Молоко")
A("")
A("Ведро молока убирает 65 % опьянения и снимает похмелье — быстрый способ протрезветь.")
A("")
A("---")
A("")
A("## 3. Блоки и как ими пользоваться")
A("")
A("| Блок | Что делает | Управление |")
A("|---|---|---|")
A("| Бродильная бочка | брожение: закваска + тара → пиво, вино, брага | ПКМ предметом — положить, ПКМ пустой рукой — забрать/узнать прогресс |")
A("| Самогонный аппарат | дистилляция: брага/вино → крепкий алкоголь. **Нужен огонь снизу** | то же |")
A("| Бочка для выдержки | выдержка: самогон → виски, ром, коньяк | то же |")
A("| Барная стойка | до 3 предметов сверху, смешивание шейкером | ПКМ напитком — поставить, ПКМ шейкером — смешать, ПКМ пустой рукой — забрать |")
A("")
A("Особенности аппаратов:")
A("")
A("* 4 слота для ингредиентов + 1 слот результата, GUI нет — всё через ПКМ и сообщения")
A("  над хотбаром (так мод остаётся совместимым с гибридными ядрами);")
A("* ПКМ с зажатым Shift кладёт весь стак, обычный ПКМ — один предмет (до 16 в слот);")
A("* под самогонный аппарат нужно поставить огонь, лаву, магму или горящую печь")
A("  (отключается опцией `machines.stillNeedsHeat`);")
A("* если рецепта нет, ПКМ пустой рукой вернёт ингредиенты;")
A("* при разрушении блока всё содержимое выпадает.")
A("")
A("Барная стойка: поставьте 2–3 напитка (или посуду) и щёлкните шейкером — если такая")
A("комбинация есть в списке смешивания, вы получите коктейль прямо в руки.")
A("")
A("---")
A("")
A("## 4. Крафты в верстаке и печи")
A("")
A("Точка `.` в схеме — пустая клетка.")
A("")
A("### 4.1 Фигурные крафты (верстак)")
A("")
A("| Результат | Схема | Обозначения |")
A("|---|---|---|")
for c in CRAFTS:
    if c["kind"] == "shaped":
        A("| %s ×%d | %s | %s |" % (ru_name(c["result"]), c["count"], schema_cell(c), legend_cell(c)))
A("")
A("### 4.2 Бесформенные крафты (верстак)")
A("")
A("| Результат | Ингредиенты |")
A("|---|---|")
for c in CRAFTS:
    if c["kind"] == "shapeless":
        A("| %s ×%d | %s |" % (ru_name(c["result"]), c["count"], ru_list(c["ingredients"])))
A("")
A("### 4.3 Печь")
A("")
A("| Результат | Из чего | Время |")
A("|---|---|---|")
for c in CRAFTS:
    if c["kind"] == "smelting":
        A("| %s ×%d | %s | %g с |" % (ru_name(c["result"]), c["count"],
                                      ru_name(c["ingredient"]), c["time"] / 20.0))
A("")
A("---")
A("")
A("## 5. Рецепты аппаратов")
A("")
for machine in ("FERMENTER", "STILL", "AGING"):
    rows = [p for p in PROCESS if p["machine"] == machine]
    if not rows:
        continue
    A("### %s" % MACHINE_RU.get(machine, machine))
    A("")
    A("| Ингредиенты (в любом порядке) | Результат | Время |")
    A("|---|---|---|")
    for p in rows:
        A("| %s | %s ×%d | %g с |" % (ru_list(p["inputs"]), ru_name(p["result"]),
                                      p["count"], p["time"] / 20.0))
    A("")
A("---")
A("")
A("## 6. Смешивание на барной стойке (шейкер)")
A("")
A("| Что поставить на стойку | Что получится |")
A("|---|---|")
for m in MIX:
    A("| %s | %s ×%d |" % (ru_list(m["inputs"]), ru_name(m["result"]), m["count"]))
A("")
A("---")
A("")
A("## 7. Все напитки (%d шт.)" % len(DRINKS))
A("")
for cat in CAT_ORDER:
    rows = [d for d in DRINKS if d["cat"] == cat]
    if not rows:
        continue
    A("### %s" % CAT_RU.get(cat, cat))
    A("")
    A("| Название | ID | Тара | Крепость | Эффекты в начале | Прочее |")
    A("|---|---|---|---|---|---|")
    for d in rows:
        A("| %s | `%s` | %s | %s | %s | %s |" % (
            d["ru"], d["id"], VESSEL_RU.get(g(d, "vessel", "NONE"), "—"),
            abv_text(d), fx_text(d), extra_text(d)))
    A("")
A("После выпивания тара возвращается в инвентарь: бутылка → стеклянная бутыль,")
A("стакан/кружка/рюмка → своя посуда, банка → пустая банка (её можно переплавить в самородок).")
A("")
A("---")
A("")
A("## 8. Предметы и посуда")
A("")
A("| Предмет | ID | Для чего |")
A("|---|---|---|")
TOOL_PURPOSE = {
    "glass_cup": "тара для коктейлей, газировки и соков",
    "mug": "тара для пива, браги и кофе",
    "shot_glass": "тара для крепкого алкоголя",
    "empty_can": "тара для газировки и энергетиков",
    "shaker": "смешивание напитков на барной стойке",
    "coffee_beans": "кофе, энергетики, эспрессо",
    "yeast": "нужны для любой закваски",
    "soda_syrup": "основа газировки",
    "energy_syrup": "основа энергетиков",
}
for t in TOOLS:
    A("| %s | `%s` | %s |" % (t["ru"], t["id"], TOOL_PURPOSE.get(t["id"], "—")))
A("")
A("---")
A("")
A("## 9. Эффекты мода")
A("")
A("| Эффект | ID | Когда появляется |")
A("|---|---|---|")
EFFECT_WHEN = {
    "tipsy": "шкала алкоголя от 1",
    "drunk": "шкала от 20",
    "heavy_drunk": "шкала от 55",
    "passed_out": "игрока уложило",
    "hangover": "после сильного опьянения",
    "withdrawal": "зависимость + 10 минут без алкоголя",
    "caffeine": "кофе и энергетики",
    "jitters": "кофеин выше 80",
}
for e in EFFECTS:
    A("| %s | `boozecraft:%s` | %s |" % (e["ru"], e["id"], EFFECT_WHEN.get(e["id"], "—")))
A("")
A("---")
A("")
A("## 10. Команды и права")
A("")
A("| Команда | Что делает | Права |")
A("|---|---|---|")
A("| `/booze status` | показать свои значения | все |")
A("| `/booze status <игрок>` | значения другого игрока | оператор (2) |")
A("| `/booze set <игрок> <0-1000>` | выставить опьянение | оператор (2) |")
A("| `/booze addiction <игрок> <0-100>` | выставить зависимость | оператор (2) |")
A("| `/booze caffeine <игрок> <0-200>` | выставить кофеин | оператор (2) |")
A("| `/booze sober <игрок>` | полностью протрезвить | оператор (2) |")
A("| `/booze passout <игрок> <сек>` | уложить игрока | оператор (2) |")
A("| `/booze wake <игрок>` | поднять игрока | оператор (2) |")
A("")
A("LuckPerms на гибридном сервере: право на команду — `minecraft.command.booze`,")
A("для укладывания игрокам нужен `gsit.lay`.")
A("")
A("---")
A("")
A("## 11. Конфиг `config/boozecraft-server.toml`")
A("")
A("| Опция | По умолчанию | Значение |")
A("|---|---|---|")
A("| `drunkThreshold` | 20 | порог опьянения |")
A("| `heavyDrunkThreshold` | 55 | порог сильного опьянения |")
A("| `soberRatePerSecond` | 0.18 | скорость протрезвления |")
A("| `alcoholCap` | 150 | максимум шкалы |")
A("| `drinkStrengthMultiplier` | 1.0 | общий множитель крепости |")
A("| `starterEffectsOnlyWhenSober` | true | приятные эффекты только пока трезв |")
A("| `statusMessages` | true | сообщения о состоянии над хотбаром |")
A("| `stumble` | true | шатание при ходьбе |")
A("| `vomit` / `vomitChancePerSecond` | true / 0.02 | рвота при сильном опьянении |")
A("| `passOut.enabled` | true | вырубание вообще |")
A("| `passOut.chancePerSecond` | 0.012 | шанс вырубиться в секунду |")
A("| `passOut.secondsMin` / `secondsMax` | 20 / 45 | сколько лежать |")
A("| `passOut.commands` | `lay` | команды при вырубании (через `;`, `%player%`) |")
A("| `passOut.endCommands` | пусто | команды при пробуждении (например `getup`) |")
A("| `passOut.reapplyCommand` | true | не давать встать раньше времени |")
A("| `passOut.blindness` | true | слепота во время сна |")
A("| `passOut.forcePoseFallback` | true | своя поза лежа, если плагина нет |")
A("| `hangover.enabled` / `seconds` | true / 180 | похмелье |")
A("| `addiction.enabled` | true | зависимость |")
A("| `addiction.threshold` | 40 | порог зависимости |")
A("| `addiction.gainMultiplier` | 1.0 | скорость набора зависимости |")
A("| `addiction.decayPerMinute` | 0.8 | спад зависимости за минуту трезвости |")
A("| `addiction.withdrawalDelaySeconds` | 600 | через сколько начнётся абстиненция |")
A("| `caffeine.soberFactor` | 0.25 | насколько кофеин трезвит |")
A("| `caffeine.decayPerSecond` | 0.35 | спад кофеина |")
A("| `caffeine.jittersThreshold` | 80 | порог тремора |")
A("| `machines.speedMultiplier` | 1.0 | скорость аппаратов |")
A("| `machines.stillNeedsHeat` | true | самогонному аппарату нужен огонь |")
A("")
A("`config/boozecraft-client.toml`: `visuals.cameraSway` (true) и")
A("`visuals.cameraSwayStrength` (1.0) — покачивание камеры у пьяного игрока.")
A("")
A("---")
A("")
A("## 12. Сборка из исходников")
A("")
A("Нужен только **JDK 21** и интернет (Gradle скачается сам).")
A("")
A("* **GitHub Actions (без установки чего-либо):** загрузите папку в репозиторий →")
A("  вкладка *Actions* → workflow `build` → готовый jar в *Artifacts*.")
A("* **Linux/macOS:** `./build.sh`")
A("* **Windows:** двойной клик по `build.bat`")
A("* **IntelliJ IDEA:** *Open* → выбрать папку → Gradle всё подтянет сам,")
A("  запуски `runClient` / `runServer` уже настроены.")
A("")
A("Готовый файл появится в `build/libs/boozecraft-1.0.0.jar`.")
A("")
A("---")
A("")
A("## 13. Частые вопросы")
A("")
A("**Нужен ли мод игрокам?** Да, это обычный мод: jar ставится и на сервер, и на клиент.")
A("")
A("**Работает ли на Youer?** Да. Мод не трогает внутренности сервера, только ванильные")
A("механики и команды, поэтому гибридные ядра его переваривают без патчей.")
A("")
A("**Можно ли выключить вырубание?** `passOut.enabled = false` в серверном конфиге.")
A("")
A("**Как заменить `lay` на другой плагин?** Впишите свои команды в `passOut.commands`,")
A("например `sit` или `gsit lay %player%`. Несколько команд разделяются `;`.")
A("")
A("**Где хранится опьянение?** В файле мира `boozecraft_players.json`, автосохранение")
A("каждые 2 минуты и при выходе игрока/остановке сервера.")
A("")

write(os.path.join(ROOT, "DOCUMENTATION.md"), "\n".join(L))
print("documentation written: %d lines" % len(L))

README = []
R = README.append
R("# BoozeCraft")
R("")
R("Алкоголь, газировка, энергетики, кофе, посуда, барная стойка и полноценная система")
R("опьянения для **Minecraft 1.21.1 / NeoForge 21.1.248**.")
R("")
R("* %d напитка, %d предмета, %d блока, %d эффекта" % (len(DRINKS), len(TOOLS), len(BLOCKS), len(EFFECTS)))
R("* %d крафтов, %d рецептов аппаратов, %d рецептов смешивания" % (len(CRAFTS), len(PROCESS), len(MIX)))
R("* мультиплеер и гибридные сервера (Youer, Mohist, Arclight)")
R("* вырубание пьяного игрока через GSit (`lay`), встать раньше времени нельзя")
R("")
R("Полное описание крафтов, механик и конфига — в [DOCUMENTATION.md](DOCUMENTATION.md).")
R("")
R("## Быстрая сборка")
R("")
R("Нужен JDK 21.")
R("")
R("```bash")
R("./build.sh          # Linux / macOS")
R("build.bat           # Windows")
R("```")
R("")
R("Или без установки инструментов: загрузите проект на GitHub — workflow `build`")
R("соберёт jar и положит его в Artifacts.")
R("")
R("Результат: `build/libs/boozecraft-1.0.0.jar` → в папку `mods` сервера и клиента.")
R("")
R("## Структура")
R("")
R("```")
R("src/main/java/com/s4fmer/boozecraft/   исходники мода")
R("src/main/resources/                    модели, тексты, рецепты, текстуры")
R("tools/                                 генераторы контента (Python)")
R("DOCUMENTATION.md                       документация на русском")
R("```")
R("")
write(os.path.join(ROOT, "README.md"), "\n".join(README))
print("readme written")
